### ISSUE TITLE
Adding OpenTracing support for Kata

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#27] opened 2018-07-31 16:08 UTC
All Kata Components use highly [structured logging](https://github.com/sirupsen/logrus).

We now need to consider adding full tracing abilities using [OpenTracing](http://opentracing.io) as we can leverage the existing tooling and capitalise on the log fields we've added.

I've only started to look at open tracing but it sounds like we're going to have to think very carefully about where we inject traces and spans to get the maximum benefit.

**Comment by jodh-intel** [comment] 2018-07-31 16:08
If anyone has experience of open tracing, please feel free to add thoughts here :)

/cc @sameo, @egernst.

**Comment by jodh-intel** [comment] 2018-08-01 15:59
After a bit of reading, the mists are starting to clear... a little. Here are my thoughts+findings so far on adding opentracing support to Kata. I'd really appreciate input from folk conversant in opentracing though :)...

# Rough plan

- general
  - [ ] Use [jaeger](https://github.com/jaegertracing/jaeger-client-go).
  - [ ] Replace all the current `context.Background()` calls with the contact passed into each function.
  - [ ] Add a `context.Context` parameter to most functions to allow the tracing context to be passed throughout the codebase (Google best practice and effectively a requirement for using opentracing fully).

- agent
  - [ ] Update to specify a context+tracer for for client (`Dial*()`) and server (`NewServer()`) functions.
   (https://godoc.org/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc#LogPayloads can be used to remove the existing custom gRPC tracer).
  - [ ] Find a way to get the traces back to the host (see below).

- runtime
  - [ ] Add tracing options to `configuration.toml` (see below).
  - [ ] Initialise tracing.
  - [ ] Create a *single* trace and a single span in `main()`, add to context and pass to all (CLI) functions.
    Those functions will consume the provided context and create their own spans as needed.

- virtcontainers
  - [ ] Update all functions in `api.go` to accept a `context.Context` as their first argument.
  - [ ] Add a `context.Context` to most of the other functions too (big job!)

- shim:
  - [ ] FIXME: see below.

- proxy:
  - [ ] FIXME: see below.

- network monitor:
  - [ ] FIXME: see below.

- throttler:
  - [ ] FIXME: see below.

# Questions

- How do we get the agent traces *out* of the VM?
  - Expose a qemu socket mapped back to a host socket where the opentracing recorder is running?
    (security concerns)
  - ?

- How do we handle tracing the proxy and shim (and [network monitor](https://github.com/kata-containers/runtime/pull/534) and [throttler](https://github.com/kata-containers/ksm-throttler))?

  The runtime is a short-lived process wheras the proxy and shim processes are longer-lived. Further, the runtime/vc communicates with them initially via CLI options. We could serialise the trace span and pass it to each component but that feels horribly wrong. Also, since the runtime is short-lived, it will be `Finish()` it's spans *before* the proxy/shim finishes. This implies the proxy/shim need to create their own traces. However, I don't see how opentracing is going to allow us to associate the runtime call path with these external processes as they will be using different traces. We currently associate log entries across all components using the containerID and sandboxID.

  I'm not clear how the proxy + shim will work. We can pass the span details to their CLI to allow them to reconstruct (I think) the context, but those context will not be valid (since the runtime/vc will have called `span.Finish()`) That implies these two components will need to create their own traces. But it's not clear to me how the tracing framework will then associate those traces with the main trace?

- Given opentracing is a standard, not an implementation, what tracing options do we need in `configuration.toml`?

# Follow-on work

- Simplify our logging?
  - Migrate log fields to the trace spans.
  - Look at [`zap`](https://github.com/uber-go/zap) as a (faster) alternative to [`logrus`](https://godoc.org/github.com/sirupsen/logrus).

**Comment by grahamwhaley** [comment] 2018-08-02 10:40
All of that sounds sane to me. Also, as you point out, adding those `Context`s throughout the code base sounds like a fair amount of (necessary) work.

I can see there is a myriad of links one could spend hours following to get a handle on Jaeger, OpenTracing etc. Do you happen to have a link for a quick overview or example or maybe video one could peruse to get an overview? I see OpenTracing is designed for log/diagnosis of distributed apps, which feels almost exactly like what we have, even if all the components are on the same machine. Thus, I'm going to presume it can handle the data coming from different sources and correlate/combine those into a single trace/view.
Maybe - you can contemplate doing us an OpenTracing overview wrt Kata in a Monday Arch Committee call @jodh-intel ?

It's sounding good - quite promising and exciting :-)

**Comment by jodh-intel** [comment] 2018-08-02 10:47
I'm afraid I don't have a good link - I've spent hours scouring info from lots of places.

That might be an idea, but as I've pointed out above, I have only just started looking at what is a complex subject. Hence, it could take some time!

I wonder if @tallclair or @jon might have thoughts on the rough design sketch / questions above?

**Comment by jodh-intel** [comment] 2018-08-08 10:44
https://github.com/kata-containers/kata-containers/issues/27#issuecomment-409625655 updated with latest findings.

**Comment by jodh-intel** [comment] 2018-08-09 14:32
Related: https://github.com/kata-containers/runtime/issues/566

**Comment by jodh-intel** [comment] 2018-08-09 16:57
Added "Priorities" section to https://github.com/kata-containers/kata-containers/issues/27#issuecomment-409625655.

**Comment by jodh-intel** [comment] 2018-08-13 16:27
Thanks @dagrh - I think that is probably the best option right now given the constraints around vsock availability. I've added this info to https://github.com/kata-containers/agent/issues/322.

**Comment by jodh-intel** [comment] 2018-08-21 13:40
Some interesting initial observations based on looking at the trace results by running https://github.com/kata-containers/runtime/pull/617 under docker:

| CLI command | Slowest operation | Needs investigation? | Notes |
|--|--|--|--|
| `create` | [First gRPC call](https://github.com/kata-containers/runtime/blob/0c0e17f92440abe75a7cae89c22b14e600e51028/virtcontainers/kata_agent.go#L583) | Yes | Likely caused by the gRPC layer waiting for the VM to boot.
| `start` | [Container start in agent](https://github.com/kata-containers/runtime/blob/0c0e17f92440abe75a7cae89c22b14e600e51028/virtcontainers/kata_agent.go#L1103)| Maybe | Operation is generally fast. |
| `state` | [Unmounting host bind mounts](https://github.com/kata-containers/runtime/blob/0c0e17f92440abe75a7cae89c22b14e600e51028/virtcontainers/container.go#L505) | Yes | Huge variation in times (can be ~40 times slower than "normal"). |
| `kill` | [Fetching a state file from disk](https://github.com/kata-containers/runtime/blob/0c0e17f92440abe75a7cae89c22b14e600e51028/virtcontainers/filesystem.go#L637)| Maybe | Operation is generally fast but might be worth investigating database backends. |
| `delete` | [Removing network interfaces](https://github.com/kata-containers/runtime/blob/0c0e17f92440abe75a7cae89c22b14e600e51028/virtcontainers/sandbox.go#L979)  | Yes | CNM networking. |

/cc @bergwolf, @sboeuf, @mcastelino, @amshinde.

**Comment by jodh-intel** [comment] 2018-08-23 14:42
# Agent update

## Background: Jaeger architecture

- The Jaeger architecture nominally requires "every host" to run an instance of the [Jaeger agent](https://github.com/jaegertracing/jaeger/tree/master/cmd/agent).

- The Jaeger [client library](https://godoc.org/github.com/uber/jaeger-client-go) then talks to the Jaeger agent over UDP.

- The Jaeger agent then sends the trace spans to the [Jaeger collector](https://github.com/jaegertracing/jaeger/tree/master/cmd/collector) over TCP.

## Kata requirements

- At most a single Jaeger agent running on the host (the environment where the `kata-runtime` is executed).

- Allow the Jaeger client library bound into the `kata-agent` running in the VM to "talk out" to the single Jaeger agent running on the host.
  
  In other words, we don't want to run a Jaeger agent inside the VM (host), as that would bloat the image. Further, it would be redundant unless tracing was enabled.

## Options

### 1) Redirect UDP guest -> host comms

The ideal solution would be to transparently redirect a guest UDP port to a host UDP port. That would allow the Jaeger client library to "talk out" of the VM to an unmodified Jaeger agent running on the host.

I've tried playing around with qemu options and the key seems to be `-net user,guestfwd`. That option allows transparent guest -> host redirection.

### 2) Modify qemu to allow UDP guestfwd

The qemu `-net user,guestfwd` option currently only supports TCP. It's unclear to me why but this *seems* to be "by design". However, we could explore the possibility of enabling UDP support.

### 3) Modify Jaeger

We could conceivably enhance the Jaeger client library and Jaeger agent to support one (or both) of the two VM-specific guest->host communication methods:

- [`virtio-serial`](https://fedoraproject.org/wiki/Features/VirtioSerial)
- [`virtio-vsock`](https://wiki.qemu.org/Features/VirtioVsock) (VSOCK)

Both `virtio-serial` and `virtio-vsock` solutions allow comms even when the VM does not have a network.

VSOCK would probably be the cleanest solution as it's "just another socket type". However, VSOCK does require a Linux 4.8 host kernel (`vhost_vsock` kernel module) which may be an issue for some users.

-----

Since the Kata Project is moving towards VSOCK (see for example https://github.com/kata-containers/runtime/pull/497), assuming the Jaeger project are happy with the approach, I think we should consider adding VSOCK (and then maybe virtio-serial) support to Jaeger.

I'll raise an issue on Jaeger and reference here to track the Jaeger projects thoughts on this plan...

/cc @mcastelino, @sameo, @sboeuf, @devimc, @anthonyzxu, @stefanha, @bergwolf, @gnawux, @dagrh, @grahamwhaley.

**Comment by devimc** [comment] 2018-08-23 15:00
@jodh-intel IMO the best option is to modify jaeger, looking forward to see your issue in Jaeger :smiley:

**Comment by stefanha** [comment] 2018-08-23 15:06
QEMU's `-net user` feature is not considered supported from a security perspective.  It is not a production-quality feature and presents an attack surface that should be avoided.

I think VSOCK is appropriate for this scenario.

Only SOCK_STREAM is supported by virtio-vsock at this time.  If datagram (SOCK_DGRAM) semantics are needed then additional work may be necessary to either frame datagrams over a SOCK_STREAM connection or to implement SOCK_DGRAM for virtio-vsock.

**Comment by jodh-intel** [comment] 2018-08-23 15:19
Jaeger issue is https://github.com/jaegertracing/jaeger/issues/1019.

**Comment by jodh-intel** [comment] 2018-08-23 15:31
Thanks @stefanha - I think `SOCK_DGRAM` is more aligned with the existing Jaeger client -> agent UDP comms. However, `SOCK_STREAM` sounds like a good initial approach.

**Comment by WeiZhang555** [comment] 2018-08-24 01:37
This sounds good!


> Both virtio-serial and virtio-vsock solutions allow comms even when the VM does not have a network.

Yes, please always consider the case without vsock support, as 4.8 is sometimes too new for some users.


发件人: James O. D. Hunt [mailto:notifications@github.com]
发送时间: 2018年8月23日 22:43
收件人: kata-containers/kata-containers <kata-containers@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: Re: [kata-containers/kata-containers] Adding OpenTracing support for Kata (#27)

Agent update
Background: Jaeger architecture

·         The Jaeger architecture nominally requires "every host" to run an instance of the Jaeger agent<https://github.com/jaegertracing/jaeger/tree/master/cmd/agent>.

·         The Jaeger client library<https://godoc.org/github.com/uber/jaeger-client-go> then talks to the Jaeger agent over UDP.

·         The Jaeger agent then sends the trace spans to the Jaeger collector<https://github.com/jaegertracing/jaeger/tree/master/cmd/collector> over TCP.

Kata requirements

·         At most a single Jaeger agent running on the host (the environment where the kata-runtime is executed).

·         Allow the Jaeger client library bound into the kata-agent running in the VM to "talk out" to the single Jaeger agent running on the host.

In other words, we don't want to run a Jaeger agent inside the VM (host), as that would bloat the image. Further, it would be redundant unless tracing was enabled.

Options
1) Redirect UDP guest -> host comms

The ideal solution would be to transparently redirect a guest UDP port to a host UDP port. That would allow the Jaeger client library to "talk out" of the VM to an unmodified Jaeger agent running on the host.

I've tried playing around with qemu options and the key seems to be -net user,guestfwd. That option allows transparent guest -> host redirection.

2) Modify qemu to allow UDP guestfwd

The qemu -net user,guestfwd option currently only supports TCP. It's unclear to me why but this seems to be "by design". However, we could explore the possibility of enabling UDP support.

3) Modify Jaeger

We could conceivably enhance the Jaeger client library and Jaeger agent to support one (or both) of the two VM-specific guest->host communication methods:

  *   virtio-serial<https://fedoraproject.org/wiki/Features/VirtioSerial>
  *   virtio-vsock<https://wiki.qemu.org/Features/VirtioVsock> (VSOCK)

Both virtio-serial and virtio-vsock solutions allow comms even when the VM does not have a network.

VSOCK would probably be the cleanest solution as it's "just another socket type". However, VSOCK does require a Linux 4.8 host kernel (vhost_vsock kernel module) which may be an issue for some users.

________________________________

Since the Kata Project is moving towards VSOCK (see for example kata-containers/runtime#497<https://github.com/kata-containers/runtime/pull/497>), assuming the Jaeger project are happy with the approach, I think we should consider adding VSOCK (and then maybe virtio-serial) support to Jaeger.

I'll raise an issue on Jaeger and reference here to track the Jaeger projects thoughts on this plan...

/cc @mcastelino<https://github.com/mcastelino>, @sameo<https://github.com/sameo>, @sboeuf<https://github.com/sboeuf>, @devimc<https://github.com/devimc>, @anthonyzxu<https://github.com/anthonyzxu>, @stefanha<https://github.com/stefanha>, @bergwolf<https://github.com/bergwolf>, @gnawux<https://github.com/gnawux>, @dagrh<https://github.com/dagrh>, @grahamwhaley<https://github.com/grahamwhaley>.

**Comment by jodh-intel** [comment] 2018-09-05 11:02
Brief update on https://github.com/jaegertracing/jaeger/issues/1019: it's blocked on two other Jaeger issues (to refactor agent config and support plugins).

**Comment by jodh-intel** [comment] 2018-09-28 15:53
Looking https://github.com/kata-containers/kata-containers/issues/27#issuecomment-414677578 above, specifically "Removing network interfaces", I did a bit of more in-depth tracing and ended up having to use perf/ftrace:

```
$ sudo perf ftrace -vvv -t function_graph -G syscalls:sys_enter_umount -a > ftrace.log
```
That showed the following (not the large amount of time spent in `do_umount()`):

```
 1)               |              drop_mountpoint() {
 1)               |                dput() {
 1)               |                  dput.part.23() {
 1)               |                    _cond_resched() {
 1)   0.049 us    |                      rcu_all_qs();
 1)   0.501 us    |                    }
 1)   0.973 us    |                  }
 1)   1.411 us    |                }
 1)               |                pin_remove() {
 1)   0.050 us    |                  _raw_spin_lock();
 1)   0.048 us    |                  _raw_spin_lock_irq();
 1)               |                  __wake_up_locked() {
 1)   0.056 us    |                    __wake_up_common();
 1)   0.515 us    |                  }
 1)   1.923 us    |                }
 1)               |                mntput_no_expire() {
 1)   0.053 us    |                  _raw_spin_lock();
 1)   0.256 us    |                  mnt_get_count();
 1)   1.289 us    |                }
 1)   5.856 us    |              }
 1)   6.890 us    |            }
 1) ! 134.997 us  |          }
 1) * 67319.17 us |        } /* namespace_unlock */
 1) * 67698.66 us |      } /* do_umount */
 1)               |      dput() {
 1)               |        dput.part.23() {
 1)               |          _cond_resched() {
 1)   0.052 us    |            rcu_all_qs();
 1)   0.516 us    |          }
 1)   1.080 us    |        }
 1)   1.540 us    |      }
 1)               |      mntput_no_expire() {
 1)   0.052 us    |        _raw_spin_lock();
 1)   0.113 us    |        mnt_get_count();
 1)   0.057 us    |        task_work_add();
 1)   1.516 us    |      }
 1) * 67740.28 us |    } /* SyS_umount */
 1)               |    exit_to_usermode_loop() {

```

... which @grahamwhaley helpfully traced back to:

- https://lists.linuxfoundation.org/pipermail/containers/2016-August/037370.html

**Comment by jodh-intel** [comment] 2018-12-06 11:11
If you look at https://github.com/kata-containers/kata-containers/issues/27#issuecomment-409625655, you'll see that most of the work is now done (although some of the PRs haven't yet landed).

I'm actually wondering if we need to add trace code to the proxy (https://github.com/kata-containers/proxy/issues/103) because if you want to do "end-to-end" tracing, you will want to enable agent tracing. But to use agent tracing you need to use vsock. And if you enable vsock, that will disable the proxy entirely.

If we do add proxy tracing, you could only trace runtime+proxy+shim.

wdyt @grahamwhaley, @egernst, @gnawux, @sboeuf, @bergwolf ? Is there any value in adding tracing to the proxy?

**Comment by sboeuf** [comment] 2018-12-06 19:49
@jodh-intel I think there's always value in adding tracing as this would help any user/dev to debug faster. Even if VSOCK should be the preferred way to use Kata, we still want to support the use case where the host does not support vsock and we should not have a bad tracing experience for this use case. So yes I think adding tracing to the proxy would be great.

On a different topic, is there any way we could have agent tracing being passed through the VM by using virtio-serial? This would provide full tracing for non-vsock use case.

**Comment by jodh-intel** [comment] 2018-12-07 08:39
Ack. virtio-serial idea captured on #34 - that can be a follow-on as I'm keen to get all the tracing PRs landed for "phase 1" ;)

**Closed** 2021-04-07 09:03 UTC
Labels: feature, high-priority
