### ISSUE TITLE
CRIO network connectivity tests are failing

### ISSUE THREAD

**Issue by egernst** [kata-containers/kata-containers#868] opened 2020-10-06 23:18 UTC
# Description of problem

Seems networking is broken, at least in our testing setup for CI with CRIO + Kube

When testing the nginx-deployment with runc, I see that this test case still fails: https://github.com/kata-containers/tests/blob/master/integration/kubernetes/nginx.bats

Similarly, when running an ubuntu pod, I am unable to run apt-get update (with both kata and runc as the runtime).

ie: Kubectl apply:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: kata-bb
spec:
  containers:
  - name: bb
    image: ubuntu
    command: ["sh"]
    args: ["-c", "sleep infinity"]
    #  runtimeClassName: kata
```

Then Kubectl exec -it kata-bb -- bash
 apt-get update <hangs>

# Expected result

All the things are good

# Actual result

No connectivity

# Further information

This is all working on containerd.

```
$ crio --version
crio version 1.17.0-dev
commit: 0eec454168e381e460b3d6de07bf50bfd9b0d082
```

**Comment by fidencio** [comment] 2020-10-07 09:04
I've done quite a bunch of tests Yesterday and it's **not** an issue with Kata, instead it's an issue with the CentOS image we're using on Azure.

Basically, seems that we're using a too old image and when running `yum -y update` something is brought in that may require a reboot (to get the new kernel in) on the system in order to work properly. My guess is here is the iptables / nft switch that happened.

Things will not work till a reboot happens, and @egernst was able to test it (thanks, by the way).

@GabyCT, @chavafg, is there some way to ensure we're getting the latest CentOS releases on Azure?

**Comment by fidencio** [comment] 2020-10-07 21:30
Adding more info here.
Today I got a new VM (thanks @GabyCT) running a newer version of CentOS and the test still fails (partially).

The interesting fact is, it only fails while I don't reboot the VM. If I, for some reason, reboot the VM, tests are happy with absolutely no change. Interesting, no?

In the beginning of our setup script we perform a `yum -y update`, which results in:
```
[root@testcentos tests]# yum history info 3
Transaction ID : 3
Begin time     : Wed 07 Oct 2020 19:46:21 UTC
Begin rpmdb    : 565:8147a128b25bdfa3b93445c1660e5306ac56b968
End time       : Wed 07 Oct 2020 19:49:04 UTC (163 seconds)
End rpmdb      : 569:384d04e3a1e18eea1f8b2d9d7e33be1464eed634
User           : Cloud User <testcentos>
Return-Code    : Success
Releasever     : 8
Command Line   : -y update
Packages Altered:
    Install  grub2-tools-efi-1:2.02-87.el8_2.x86_64             @BaseOS
    Install  kernel-4.18.0-193.19.1.el8_2.x86_64                @BaseOS
    Install  kernel-core-4.18.0-193.19.1.el8_2.x86_64           @BaseOS
    Install  kernel-modules-4.18.0-193.19.1.el8_2.x86_64        @BaseOS
    Upgrade  NetworkManager-1:1.22.8-5.el8_2.x86_64             @BaseOS
    Upgraded NetworkManager-1:1.22.8-4.el8.x86_64               @@System
    Upgrade  NetworkManager-libnm-1:1.22.8-5.el8_2.x86_64       @BaseOS
    Upgraded NetworkManager-libnm-1:1.22.8-4.el8.x86_64         @@System
    Upgrade  NetworkManager-team-1:1.22.8-5.el8_2.x86_64        @BaseOS
    Upgraded NetworkManager-team-1:1.22.8-4.el8.x86_64          @@System
    Upgrade  NetworkManager-tui-1:1.22.8-5.el8_2.x86_64         @BaseOS
    Upgraded NetworkManager-tui-1:1.22.8-4.el8.x86_64           @@System
    Upgrade  bind-export-libs-32:9.11.13-6.el8_2.1.x86_64       @BaseOS
    Upgraded bind-export-libs-32:9.11.13-3.el8.x86_64           @@System
    Upgrade  bpftool-4.18.0-193.19.1.el8_2.x86_64               @BaseOS
    Upgraded bpftool-4.18.0-193.6.3.el8_2.x86_64                @@System
    Upgrade  ca-certificates-2020.2.41-80.0.el8_2.noarch        @BaseOS
    Upgraded ca-certificates-2019.2.32-80.0.el8_1.noarch        @@System
    Upgrade  centos-gpg-keys-8.2-2.2004.0.2.el8.noarch          @BaseOS
    Upgraded centos-gpg-keys-8.2-2.2004.0.1.el8.noarch          @@System
    Upgrade  centos-release-8.2-2.2004.0.2.el8.x86_64           @BaseOS
    Upgraded centos-release-8.2-2.2004.0.1.el8.x86_64           @@System
    Upgrade  centos-repos-8.2-2.2004.0.2.el8.x86_64             @BaseOS
    Upgraded centos-repos-8.2-2.2004.0.1.el8.x86_64             @@System
    Upgrade  dbus-1:1.12.8-10.el8_2.x86_64                      @BaseOS
    Upgraded dbus-1:1.12.8-9.el8.x86_64                         @@System
    Upgrade  dbus-common-1:1.12.8-10.el8_2.noarch               @BaseOS
    Upgraded dbus-common-1:1.12.8-9.el8.noarch                  @@System
    Upgrade  dbus-daemon-1:1.12.8-10.el8_2.x86_64               @BaseOS
    Upgraded dbus-daemon-1:1.12.8-9.el8.x86_64                  @@System
    Upgrade  dbus-libs-1:1.12.8-10.el8_2.x86_64                 @BaseOS
    Upgraded dbus-libs-1:1.12.8-9.el8.x86_64                    @@System
    Upgrade  dbus-tools-1:1.12.8-10.el8_2.x86_64                @BaseOS
    Upgraded dbus-tools-1:1.12.8-9.el8.x86_64                   @@System
    Upgrade  dnf-4.2.17-7.el8_2.noarch                          @BaseOS
    Upgraded dnf-4.2.17-6.el8.noarch                            @@System
    Upgrade  dnf-data-4.2.17-7.el8_2.noarch                     @BaseOS
    Upgraded dnf-data-4.2.17-6.el8.noarch                       @@System
    Upgrade  dnf-plugins-core-4.0.12-4.el8_2.noarch             @BaseOS
    Upgraded dnf-plugins-core-4.0.12-3.el8.noarch               @@System
    Upgrade  grub2-common-1:2.02-87.el8_2.noarch                @BaseOS
    Upgraded grub2-common-1:2.02-81.el8.noarch                  @@System
    Upgrade  grub2-efi-x64-1:2.02-87.el8_2.x86_64               @BaseOS
    Upgraded grub2-efi-x64-1:2.02-81.el8.x86_64                 @@System
    Upgrade  grub2-pc-1:2.02-87.el8_2.x86_64                    @BaseOS
    Upgraded grub2-pc-1:2.02-81.el8.x86_64                      @@System
    Upgrade  grub2-pc-modules-1:2.02-87.el8_2.noarch            @BaseOS
    Upgraded grub2-pc-modules-1:2.02-81.el8.noarch              @@System
    Upgrade  grub2-tools-1:2.02-87.el8_2.x86_64                 @BaseOS
    Upgraded grub2-tools-1:2.02-81.el8.x86_64                   @@System
    Upgrade  grub2-tools-extra-1:2.02-87.el8_2.x86_64           @BaseOS
    Upgraded grub2-tools-extra-1:2.02-81.el8.x86_64             @@System
    Upgrade  grub2-tools-minimal-1:2.02-87.el8_2.x86_64         @BaseOS
    Upgraded grub2-tools-minimal-1:2.02-81.el8.x86_64           @@System
    Upgrade  initscripts-10.00.6-1.el8_2.2.x86_64               @BaseOS
    Upgraded initscripts-10.00.6-1.el8_2.1.x86_64               @@System
    Upgrade  iptables-1.8.4-10.el8_2.1.x86_64                   @BaseOS
    Upgraded iptables-1.8.4-10.el8.x86_64                       @@System
    Upgrade  iptables-ebtables-1.8.4-10.el8_2.1.x86_64          @BaseOS
    Upgraded iptables-ebtables-1.8.4-10.el8.x86_64              @@System
    Upgrade  iptables-libs-1.8.4-10.el8_2.1.x86_64              @BaseOS
    Upgraded iptables-libs-1.8.4-10.el8.x86_64                  @@System
    Upgrade  kernel-tools-4.18.0-193.19.1.el8_2.x86_64          @BaseOS
    Upgraded kernel-tools-4.18.0-193.6.3.el8_2.x86_64           @@System
    Upgrade  kernel-tools-libs-4.18.0-193.19.1.el8_2.x86_64     @BaseOS
    Upgraded kernel-tools-libs-4.18.0-193.6.3.el8_2.x86_64      @@System
    Upgrade  libcroco-0.6.12-4.el8_2.1.x86_64                   @BaseOS
    Upgraded libcroco-0.6.12-4.el8.x86_64                       @@System
    Upgrade  libdnf-0.39.1-6.el8_2.x86_64                       @BaseOS
    Upgraded libdnf-0.39.1-5.el8.x86_64                         @@System
    Upgrade  libnghttp2-1.33.0-3.el8_2.1.x86_64                 @BaseOS
    Upgraded libnghttp2-1.33.0-1.el8_0.1.x86_64                 @@System
    Upgrade  librepo-1.11.0-3.el8_2.x86_64                      @BaseOS
    Upgraded librepo-1.11.0-2.el8.x86_64                        @@System
    Upgrade  libteam-1.29-1.el8_2.2.x86_64                      @BaseOS
    Upgraded libteam-1.29-1.el8.x86_64                          @@System
    Upgrade  microcode_ctl-4:20191115-4.20200609.1.el8_2.x86_64 @BaseOS
    Upgraded microcode_ctl-4:20191115-4.20200602.2.el8_2.x86_64 @@System
    Upgrade  python3-dnf-4.2.17-7.el8_2.noarch                  @BaseOS
    Upgraded python3-dnf-4.2.17-6.el8.noarch                    @@System
    Upgrade  python3-dnf-plugins-core-4.0.12-4.el8_2.noarch     @BaseOS
    Upgraded python3-dnf-plugins-core-4.0.12-3.el8.noarch       @@System
    Upgrade  python3-hawkey-0.39.1-6.el8_2.x86_64               @BaseOS
    Upgraded python3-hawkey-0.39.1-5.el8.x86_64                 @@System
    Upgrade  python3-libdnf-0.39.1-6.el8_2.x86_64               @BaseOS
    Upgraded python3-libdnf-0.39.1-5.el8.x86_64                 @@System
    Upgrade  python3-librepo-1.11.0-3.el8_2.x86_64              @BaseOS
    Upgraded python3-librepo-1.11.0-2.el8.x86_64                @@System
    Upgrade  python3-perf-4.18.0-193.19.1.el8_2.x86_64          @BaseOS
    Upgraded python3-perf-4.18.0-193.6.3.el8_2.x86_64           @@System
    Upgrade  python3-syspurpose-1.26.20-1.el8_2.x86_64          @BaseOS
    Upgraded python3-syspurpose-1.26.17-1.el8_2.x86_64          @@System
    Upgrade  selinux-policy-3.14.3-41.el8_2.6.noarch            @BaseOS
    Upgraded selinux-policy-3.14.3-41.el8_2.4.noarch            @@System
    Upgrade  selinux-policy-targeted-3.14.3-41.el8_2.6.noarch   @BaseOS
    Upgraded selinux-policy-targeted-3.14.3-41.el8_2.4.noarch   @@System
    Upgrade  shim-x64-15-15.el8_2.x86_64                        @BaseOS
    Upgraded shim-x64-15-11.el8.x86_64                          @@System
    Upgrade  sos-3.8-7.el8_2.noarch                             @BaseOS
    Upgraded sos-3.8-6.el8_2.noarch                             @@System
    Upgrade  systemd-239-31.el8_2.2.x86_64                      @BaseOS
    Upgraded systemd-239-30.el8_2.x86_64                        @@System
    Upgrade  systemd-libs-239-31.el8_2.2.x86_64                 @BaseOS
    Upgraded systemd-libs-239-30.el8_2.x86_64                   @@System
    Upgrade  systemd-pam-239-31.el8_2.2.x86_64                  @BaseOS
    Upgraded systemd-pam-239-30.el8_2.x86_64                    @@System
    Upgrade  systemd-udev-239-31.el8_2.2.x86_64                 @BaseOS
    Upgraded systemd-udev-239-30.el8_2.x86_64                   @@System
    Upgrade  teamd-1.29-1.el8_2.2.x86_64                        @BaseOS
    Upgraded teamd-1.29-1.el8.x86_64                            @@System
    Upgrade  yum-4.2.17-7.el8_2.noarch                          @BaseOS
    Upgraded yum-4.2.17-6.el8.noarch                            @@System
    Upgrade  yum-utils-4.0.12-4.el8_2.noarch                    @BaseOS
    Upgraded yum-utils-4.0.12-3.el8.noarch                      @@System
    Upgrade  bind-libs-32:9.11.13-6.el8_2.1.x86_64              @AppStream
    Upgraded bind-libs-32:9.11.13-3.el8.x86_64                  @@System
    Upgrade  bind-libs-lite-32:9.11.13-6.el8_2.1.x86_64         @AppStream
    Upgraded bind-libs-lite-32:9.11.13-3.el8.x86_64             @@System
    Upgrade  bind-license-32:9.11.13-6.el8_2.1.noarch           @AppStream
    Upgraded bind-license-32:9.11.13-3.el8.noarch               @@System
    Upgrade  bind-utils-32:9.11.13-6.el8_2.1.x86_64             @AppStream
    Upgraded bind-utils-32:9.11.13-3.el8.x86_64                 @@System
    Upgrade  cloud-init-19.4-1.el8.7.noarch                     @AppStream
    Upgraded cloud-init-18.5-12.el8_2.2.noarch                  @@System
    Upgrade  nspr-4.25.0-2.el8_2.x86_64                         @AppStream
    Upgraded nspr-4.21.0-2.el8_0.x86_64                         @@System
    Upgrade  nss-3.53.1-11.el8_2.x86_64                         @AppStream
    Upgraded nss-3.44.0-15.el8.x86_64                           @@System
    Upgrade  nss-softokn-3.53.1-11.el8_2.x86_64                 @AppStream
    Upgraded nss-softokn-3.44.0-15.el8.x86_64                   @@System
    Upgrade  nss-softokn-freebl-3.53.1-11.el8_2.x86_64          @AppStream
    Upgraded nss-softokn-freebl-3.44.0-15.el8.x86_64            @@System
    Upgrade  nss-sysinit-3.53.1-11.el8_2.x86_64                 @AppStream
    Upgraded nss-sysinit-3.44.0-15.el8.x86_64                   @@System
    Upgrade  nss-util-3.53.1-11.el8_2.x86_64                    @AppStream
    Upgraded nss-util-3.44.0-15.el8.x86_64                      @@System
    Upgrade  python3-bind-32:9.11.13-6.el8_2.1.noarch           @AppStream
    Upgraded python3-bind-32:9.11.13-3.el8.noarch               @@System
Scriptlet output:
   1 error: lsetfilecon: (/boot/efi/EFI/centos, system_u:object_r:boot_t:s0) Operation not supported
   2 warning: /etc/cloud/cloud.cfg created as /etc/cloud/cloud.cfg.rpmnew
   3 error: lsetfilecon: (/boot/efi/EFI/centos/fonts, system_u:object_r:boot_t:s0) Operation not supported
   4 error: lsetfilecon: (/boot/efi/EFI/centos/grubx64.efi;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
   5 error: lsetfilecon: (/boot/efi/EFI/BOOT/BOOTX64.EFI;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
   6 error: lsetfilecon: (/boot/efi/EFI/BOOT/fbx64.efi;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
   7 error: lsetfilecon: (/boot/efi/EFI/centos/BOOTX64.CSV;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
   8 error: lsetfilecon: (/boot/efi/EFI/centos/mmx64.efi;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
   9 error: lsetfilecon: (/boot/efi/EFI/centos/shimx64-centos.efi;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
  10 error: lsetfilecon: (/boot/efi/EFI/centos/shimx64.efi;5f7e1b0e, system_u:object_r:boot_t:s0) Operation not supported
```

Something, something in those packages is doing something that requires a reboot. But what could it? Still to be found.

I'll setup a Debian VM tomorrow and try the same thing, I'm quite interested to know whether Debian failure would be fixed similarly. It'll help to understand which package may be causing that and what's the way to proceed.

Another interesting fact is facing this failure on CentOS but not on RHEL, but well, that's something for the future me to also check.

**Comment by GabyCT** [comment] 2020-10-08 18:56
@fidencio so I tried locally with a Debian 10 VM, I updated the kernel to `linux-image-5.7.0-0` and running the K8s tests and we have the same failure ``not ok 1 Verify nginx connectivity between pods`. I do not have any issues in doing `apt-get update` or packages issues so it seems that updating kernel version in Debian is not working.

**Comment by GabyCT** [comment] 2020-10-08 19:08
and yes, I also reboot the machine and run the tests for the second time but they are failing too (in that case)

**Comment by fidencio** [comment] 2020-10-08 20:21
@GabyCT, thanks for giving it a try!

**Comment by amshinde** [comment] 2020-10-08 21:30
@fidencio Does curl or wget work after the yum update? Besides `iptables` I am concerned about the `NetworkManager` update there.

**Comment by amshinde** [comment] 2020-10-08 21:46
@fidencio This could be a problem with iptables>1.8.
Came accross this thread in calico repository: 
https://github.com/projectcalico/calico/issues/2322#issuecomment-515239775

The suggestion is to set FELIX_IPTABLESBACKEND=NFT in Calico to tell it  to use the nftables backend.
Havent looked yet, but we may have to do something similar for flannel and give it a try.
 
Another option to try out is to try this `update-alternatives --set iptables /usr/sbin/iptables-legacy` to use the older version of iptables.

**Comment by amshinde** [comment] 2020-10-08 21:49
^ @GabyCT If you have the debian VM around, could you give the `update-alternatives` command a try?

**Comment by amshinde** [comment] 2020-10-08 23:09
Hey @fidencio, looks like this a known bug with iptables > 1.8. We are using flannel in our CI, here is a bug opened in flannel for this:
https://github.com/coreos/flannel/issues/1306


Maybe worth trying with this https://github.com/coreos/flannel/pull/1318/commits/70b109514ba2ea250830fe2ceac5b667b4fde0e3 which has been merged in flannel `v0.13.0-rc2`

**Comment by fidencio** [comment] 2020-10-09 08:34
> Hey @fidencio, looks like this a known bug with iptables > 1.8. We are using flannel in our CI, here is a bug opened in flannel for this:
> [coreos/flannel#1306](https://github.com/coreos/flannel/issues/1306)
> 
> Maybe worth trying with this [coreos/flannel@70b1095](https://github.com/coreos/flannel/commit/70b109514ba2ea250830fe2ceac5b667b4fde0e3) which has been merged in flannel `v0.13.0-rc2`

You simply nailed it down! Thanks a lot for that!

**Comment by fidencio** [comment] 2020-10-09 10:20
I'm closing this one, thanks everyone involved here!

**Closed by fidencio** 2020-10-09 10:20 UTC
Labels: bug, needs-review

**Comment by jclab-joseph** [comment] 2021-08-24 13:14
I'll try flannel later. But since I already have to use calico in my cluster, I want to find a workaround.
Is there anything I can do to help to determine the cause?
