### ISSUE TITLE
Error while running QAT with kata-containers

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/kata-containers#3214] opened 2021-12-06 16:55 UTC
We are getting an error while running the QAT tests on Ubuntu 20.04, it seems that `containerd` is passing all the host devices even when we are using the following flag `privileged_without_host_devices = true` . We are using the `kata-runtime` version `ce75785d873a6b809dce7df4f123d6d32c0a02b7`, as we are using the CI setup scripts we are installing `containerd` from the tarball https://github.com/containerd/containerd/releases/download/v1.5.2/cri-containerd-cni-1.5.2-linux-amd64.tar.gz, and the configuration.toml from `containerd` is:
```
 [debug]
   level = "debug"
 [plugins]
   [plugins.cri]
     [plugins.cri.containerd]
       [plugins.cri.containerd.runtimes]
         [plugins.cri.containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v1"
            [plugins.cri.containerd.runtimes.runc.options]
              BinaryName = "/usr/local/sbin/runc"
              Root = ""
         [plugins.cri.containerd.runtimes.kata]
            runtime_type = "io.containerd.kata.v2"
            privileged_without_host_devices = true
     [plugins.cri.registry.mirrors."localhost:5000"]
       endpoint = ["http://localhost:5000"]
```
  The error we are getting is
```
12:27:56 + sudo ctr run --runtime io.containerd.run.kata.v2 --privileged -d --rm --device=/dev/vfio/170 --mount type=bind,src=/dev,dst=/dev,options=rbind:rw --mount type=bind,src=/home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/dockerfiles/QAT/output/configs/c6xxvf_dev0.conf,dst=/etc/c6xxvf_dev0.conf,options=rbind:rw docker.io/library/openssl-qat-engine:latest qat sh -c 'tail -f /dev/null'
12:28:06 ctr: failed to create shim: Conflicting device updates for /dev/dm-0: unknown
```
We tried to revert the commit `https://github.com/kata-containers/tests/commit/d2fcba0094452add888f450fbae3a830731adb23` but the error is still the same, we also updated the host from Ubuntu 18.04 to 20.04, and we checked the `configuration.toml` from `containerd`. Any other idea of what can be causing the error?
/cc @amshinde @chavafg @devimc

**Comment by devimc** [comment] 2021-12-06 18:28
cc @eadamsintel @mythi

**Comment by mythi** [comment] 2021-12-06 19:18
@GabyCT Is my understanding correct that updating kata-runtime version makes it fail?

**Comment by GabyCT** [comment] 2021-12-06 19:58
@mythi yes that it seems correct, the last time it worked was on november 22nd

**Comment by eadamsintel** [comment] 2021-12-06 20:03
@GabyCT That seems to be a conflict with device mapper. Are you doing tests of both virtio-fs and devicemapper? I've not ever tested with device mapper before. Where there any device passthrough related patches that might be suspect?

@mythi Is there a way to further limit the devices pass into a QAT container?  On my setup I tried to pass in `/dev/qat_adf_ctl`, `/dev/qat_dev_processes`, and `/dev/usdm-drv` but it is still erroring out that I need `/dev/uio0`. If I try to make that an individual mount point in the pod yaml for that also it fails to start the pod with error "No such file or directory (os error 2)" but on the host I can see that folder. The `adf_ctl` works with those other mount points passed in but not openssl.

**Comment by fidencio** [comment] 2021-12-06 20:04
@GabyCT, how easy it'd be to bisect the agent around the date where it started happening?

Here I'm mostly interested on trying to pinpoint to one specific component that could have caused such breakage.

**Comment by fidencio** [comment] 2021-12-06 20:07
> @GabyCT, how easy it'd be to bisect the agent around the date where it started happening?
> 
> Here I'm mostly interested on trying to pinpoint to one specific component that could have caused such breakage.

I'd start, for instance, checking anything before and after #2927, as David's work is quite complex and it could (please, I'm not saying it is, but it could) introduce a regression on something that we only have a CI downstream for.  That series was merged on November 22nd, that's one of the reasons it may be related.

**Comment by devimc** [comment] 2021-12-06 20:09
@fidencio 

> @GabyCT, how easy it'd be to bisect the agent around the date where it started happening?

agent is not running, qemu is not able to start the VM because something (kata shim or containerd) is trying to pass some host devices (/dev/dm-0  or /dev/loop*) to the VM even when `privileged_without_host_devices` is set to `true`

**Comment by fidencio** [comment] 2021-12-06 20:11
> @fidencio
> 
> > @GabyCT, how easy it'd be to bisect the agent around the date where it started happening?
> 
> agent is not running, qemu is not able to start the VM because something (kata shim or containerd) is trying to pass some host devices (/dev/dm-0 or /dev/loop*) to the VM even when `privileged_without_host_devices` is set to `true`

That error comes from the agent (see: https://github.com/kata-containers/kata-containers/blob/ce75785d873a6b809dce7df4f123d6d32c0a02b7/src/agent/src/device.rs#L781), and that was introduced as part of #2927 ... https://github.com/kata-containers/kata-containers/pull/2927/files#diff-85ce7a5748f660f5d25ac1f8722cd1fee5a6ce45d19b0f6d23a28ce10f24879dR782

**Comment by GabyCT** [comment] 2021-12-06 21:53
according to @devimc if we used containerd version 1.3 is working properly

**Comment by mythi** [comment] 2021-12-07 05:15
> something (kata shim or containerd) is trying to pass some host devices (/dev/dm-0 or /dev/loop*) to the VM

I can see the test command uses that `/dev:/dev` volume mount magic.

**Closed** 2024-05-06 16:57 UTC
Labels: bug, area/vfio
