### ISSUE TITLE
Unable to start container as privileged: ctr: failed to create shim: QMP command failed: The device is not writable: Permission denied: unknown

### ISSUE THREAD

**Issue by jclab-joseph** [kata-containers/kata-containers#2467] opened 2021-08-20 00:55 UTC
# Description of problem

I want to use privileged to run docker:dind.

Unable to start container as privileged.

1. Install kata-containers using snap
  - https://github.com/kata-containers/kata-containers/blob/main/docs/install/snap-installation-guide.md
2. setup containerd
  - https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/containerd-kata.md
3. restart containerd
4. run container with privileged flag

# Actual result

```
# ctr run --runtime io.containerd.run.kata.v2 -t --rm  --privileged docker.io/library/busybox:latest hello sh
ctr: failed to create shim: QMP command failed: The device is not writable: Permission denied: unknown
```

# Further information

kata-collect: https://gist.github.com/jclab-joseph/31fb6477f63a1bc339f5aa8a6d5fa083

## Debug Log

```
Aug 20 01:01:42 microk8s-dev systemd[1]: tmp-containerd\x2dmount484168862.mount: Succeeded.
Aug 20 01:01:42 microk8s-dev virtiofsd[1674461]: virtio_session_mount: Waiting for vhost-user socket connection...
Aug 20 01:01:42 microk8s-dev virtiofsd[1674461]: virtio_session_mount: Received vhost-user socket connection
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: virtio_loop: Entry
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_set_started: qidx=0 started=1
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_set_started: qidx=1 started=1
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_thread: Start for queue 0 kick_fd 9
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_thread: Start for queue 1 kick_fd 12
Aug 20 01:01:42 microk8s-dev kata[1674451]: time="2021-08-20T01:01:42.821507636Z" level=error msg="container create failed" error="QMP command failed: The device is not writable: Permission denied" name=containerd-shim-v2 pid=1674451 sandbox=hello source=virtcontainers subsystem=container
Aug 20 01:01:42 microk8s-dev kata[1674451]: time="2021-08-20T01:01:42.82165576Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1674451 rootfs-dir=/run/kata-containers/shared/sandboxes/hello/mounts/hello/rootfs sandbox=hello source=virtcontainers subsystem=mount
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.821507636Z" level=error msg="container create failed" error="QMP command failed: The device is not writable: Permission denied" name=containerd-shim-v2 pid=1674451 sandbox=hello source=virtcontainers subsystem=container
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.821655760Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1674451 rootfs-dir=/run/kata-containers/shared/sandboxes/hello/mounts/hello/rootfs sandbox=hello source=virtcontainers subsystem=mount
Aug 20 01:01:42 microk8s-dev kata[1674451]: time="2021-08-20T01:01:42.823081853Z" level=warning msg="sandbox cgroups path is empty" name=containerd-shim-v2 pid=1674451 sandbox=hello source=virtcontainers subsystem=sandbox
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.823081853Z" level=warning msg="sandbox cgroups path is empty" name=containerd-shim-v2 pid=1674451 sandbox=hello source=virtcontainers subsystem=sandbox
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_set_started: qidx=0 started=0
Aug 20 01:01:42 microk8s-dev systemd[1848]: run-netns-cnitest\x2da4761be0\x2d314d\x2de9ac\x2ddd54\x2d0823b86a855f.mount: Succeeded.
Aug 20 01:01:42 microk8s-dev systemd[1]: run-kata\x2dcontainers-shared-sandboxes-hello-shared.mount: Succeeded.
Aug 20 01:01:42 microk8s-dev systemd[1]: run-netns-cnitest\x2da4761be0\x2d314d\x2de9ac\x2ddd54\x2d0823b86a855f.mount: Succeeded.
Aug 20 01:01:42 microk8s-dev kata[1674451]: time="2021-08-20T01:01:42.825920154Z" level=warning msg="failed to cleanup netns" error="failed to get netns /var/run/netns/cnitest-a4761be0-314d-e9ac-dd54-0823b86a855f: failed to Statfs \"/var/run/netns/cnitest-a4761be0-314d-e9ac-dd54-0823b86a855f\": no such file or directory" name=containerd-shim-v2 path=/var/run/netns/cnitest-a4761be0-314d-e9ac-dd54-0823b86a855f pid=1674451 sandbox=hello source=katautils
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.825920154Z" level=warning msg="failed to cleanup netns" error="failed to get netns /var/run/netns/cnitest-a4761be0-314d-e9ac-dd54-0823b86a855f: failed to Statfs \"/var/run/netns/cnitest-a4761be0-314d-e9ac-dd54-0823b86a855f\": no such file or directory" name=containerd-shim-v2 path=/var/run/netns/cnitest-a4761be0-314d-e9ac-dd54-0823b86a855f pid=1674451 sandbox=hello source=katautils
Aug 20 01:01:42 microk8s-dev systemd[1848]: run-kata\x2dcontainers-shared-sandboxes-hello-shared.mount: Succeeded.
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.829075518Z" level=info msg="shim disconnected" id=hello
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.829123171Z" level=warning msg="cleaning up after shim disconnected" id=hello namespace=default
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.829131904Z" level=info msg="cleaning up dead shim"
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_thread: kill event on queue 0 - quitting
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_remove_watch: TODO! fd=9
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_set_started: qidx=1 started=0
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_queue_thread: kill event on queue 1 - quitting
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: fv_remove_watch: TODO! fd=12
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: virtio_loop: Unexpected poll revents 11
Aug 20 01:01:42 microk8s-dev virtiofsd[1]: virtio_loop: Exit
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.860331285Z" level=error msg="failed to delete" cmd="/usr/local/bin/containerd-shim-kata-v2 -namespace default -address /run/containerd/containerd.sock -publish-binary /usr/bin/containerd -id hello -bundle /run/containerd/io.containerd.runtime.v2.task/default/hello delete" error="exit status 1"
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.860389733Z" level=warning msg="failed to clean up after shim disconnected" error="time=\"2021-08-20T01:01:42Z\" level=warning msg=\"failed to cleanup container\" container=hello error=\"open /run/vc/sbs/hello: no such file or directory\" name=containerd-shim-v2 pid=1674481 sandbox=hello source=containerd-kata-shim-v2\nio.containerd.kata.v2: open /run/vc/sbs/hello: no such file or directory\n: exit status 1" id=hello namespace=default
Aug 20 01:01:42 microk8s-dev containerd[1673075]: time="2021-08-20T01:01:42.860430489Z" level=error msg="copy shim log" error="read /proc/self/fd/22: file already closed"
Aug 20 01:01:42 microk8s-dev systemd[1848]: run-containerd-io.containerd.runtime.v2.task-default-hello-rootfs.mount: Succeeded.
Aug 20 01:01:42 microk8s-dev systemd[1]: run-containerd-io.containerd.runtime.v2.task-default-hello-rootfs.mount: Succeeded.
```

**Comment by egernst** [comment] 2021-08-20 04:52
Certain host devices don't make sense to pass into the VM.  Based on this, we worked with CRI runtimes, including containerd, to include a flag for indicating that host devices should not necessarily be passed w/ privileged for the given runtime handler.  See https://github.com/kata-containers/documentation/blob/master/how-to/privileged.md#containerd-and-cri

**Comment by egernst** [comment] 2021-08-20 04:52
(also, @jclab-joseph  - thanks for the detailed / well written issue!)

**Comment by fengwang666** [comment] 2021-08-20 05:29
@egernst Where can I find the list of devices that are not passed to the guest?

**Comment by jclab-joseph** [comment] 2021-08-20 05:30
@egernst Thanks for the reply.
However, I added `privileged_without_host_devices = true` and it was the same.

**Comment by jclab-joseph** [comment] 2021-08-21 15:20
Can anyone please tell me how to install kata-containers?
Both ubuntu 21.04 and 20.04 give the same error.

**Comment by devimc** [comment] 2021-08-23 13:32
@jclab-joseph you are installing it correctly, the problem is that containerd is passing **all host's devices** to kata and this is not supported, could you try with CRI-O, maybe this is a bug in containerd

**Comment by jclab-joseph** [comment] 2021-08-25 10:43
Is there any way to know which device is trying to access it?
If I find out about this I will write an issue in containerd .

**Comment by jclab-joseph** [comment] 2021-08-25 11:39
I tried with cri-o but got the same result. Stuck indefinitely at ContainerCreating.
Same "QMP command failed: The device is not writable: Permission denied" error.

```
Events:
  Type    Reason     Age        From                        Message
  ----    ------     ----       ----                        -------
  Normal  Scheduled  <unknown>  default-scheduler           Successfully assigned default/test-pod to k8s-ci-node-05102
  Normal  Pulling    6m44s      kubelet, k8s-ci-node-05102  Pulling image "busybox"
  Normal  Pulled     6m40s      kubelet, k8s-ci-node-05102  Successfully pulled image "busybox"
```

```
Aug 25 11:31:23 k8s-ci-node-05102 kata[1109090]: time="2021-08-25T11:31:23.694863441Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=virtcontainers subsystem=sandbox
Aug 25 11:31:23 k8s-ci-node-05102 crio[1090854]: time="2021-08-25T11:31:23.694863441Z" level=warning msg="sandbox's cgroup won't be updated: cgroup path is empty" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=virtcontainers subsystem=sandbox
Aug 25 11:31:23 k8s-ci-node-05102 crio[1090854]: time="2021-08-25 11:31:23.710435400Z" level=info msg="Ran pod sandbox 8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 with infra container: default/test-pod/POD" id=0e9c0793-f7e5-4cd9-8fce-4b8dcf81c0b3 name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
Aug 25 11:31:23 k8s-ci-node-05102 kata[1109090]: time="2021-08-25T11:31:23.975593438Z" level=error msg="post event" error="failed to publish event: exit status 1" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=containerd-kata-shim-v2
Aug 25 11:31:23 k8s-ci-node-05102 crio[1090854]: time="2021-08-25T11:31:23.975593438Z" level=error msg="post event" error="failed to publish event: exit status 1" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=containerd-kata-shim-v2
Aug 25 11:31:24 k8s-ci-node-05102 kata[1109090]: time="2021-08-25T11:31:24.114867806Z" level=error msg="post event" error="failed to publish event: exit status 1" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=containerd-kata-shim-v2
Aug 25 11:31:24 k8s-ci-node-05102 crio[1090854]: time="2021-08-25T11:31:24.114867806Z" level=error msg="post event" error="failed to publish event: exit status 1" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=containerd-kata-shim-v2
Aug 25 11:31:27 k8s-ci-node-05102 kata[1109090]: time="2021-08-25T11:31:27.550530506Z" level=error msg="container create failed" error="QMP command failed: The device is not writable: Permission denied" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=virtcontainers subsystem=container
Aug 25 11:31:27 k8s-ci-node-05102 kata[1109090]: time="2021-08-25T11:31:27.550948811Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1109090 rootfs-dir=/run/kata-containers/shared/sandboxes/8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8/mounts/428986a674769b8709adc8ddf46898b9ff7fd835ee0d766278542571b0903e5b/rootfs sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=virtcontainers subsystem=mount
Aug 25 11:31:27 k8s-ci-node-05102 crio[1090854]: time="2021-08-25T11:31:27.550530506Z" level=error msg="container create failed" error="QMP command failed: The device is not writable: Permission denied" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=virtcontainers subsystem=container
Aug 25 11:31:27 k8s-ci-node-05102 crio[1090854]: time="2021-08-25T11:31:27.550948811Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1109090 rootfs-dir=/run/kata-containers/shared/sandboxes/8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8/mounts/428986a674769b8709adc8ddf46898b9ff7fd835ee0d766278542571b0903e5b/rootfs sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=virtcontainers subsystem=mount
Aug 25 11:31:27 k8s-ci-node-05102 crio[1090854]: time="2021-08-25T11:31:27.551347427Z" level=warning msg="failed to cleanup rootfs mount" container-type=pod_container error="no such file or directory" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=containerd-kata-shim-v2
Aug 25 11:31:27 k8s-ci-node-05102 kata[1109090]: time="2021-08-25T11:31:27.551347427Z" level=warning msg="failed to cleanup rootfs mount" container-type=pod_container error="no such file or directory" name=containerd-shim-v2 pid=1109090 sandbox=8586bbf66879ae94d6cf858bbe03c79b83bf4b0396036082b2bba859250fbfc8 source=containerd-kata-shim-v2
```

**Comment by xinau** [comment] 2021-09-10 22:26
I'm able to confirm that this behavior is exactly the same on GCP.

**Comment by xinau** [comment] 2021-09-11 00:10
I've tested the setup by replacing containerd with cri-o with

* Ubuntu 18.04 LTS
* CRI-O 1.21
* Kata Containers 2.2.0

The following is based on this `/etc/crio/crio.conf` 

```ini
[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"
privileged_without_host_devices = true
```

While `privileged_without_host_devices = false` is set inside the `crio.conf` I'm able to reproduce the issue as seen when using containerd with this manifest.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: true
  runtimeClassName: kata
```

```console
sudo -E kubectl get events --sort-by='.metadata.managedFields[0].time'
...
5s          Normal    Scheduled                 pod/nginx                   Successfully assigned default/nginx to kata-gitlab-runner-2
2s          Normal    Pulling                   pod/nginx                   Pulling image "nginx"
0s          Normal    Pulled                    pod/nginx                   Successfully pulled image "nginx" in 1.567944268s
0s          Warning   Failed                    pod/nginx                   Error: CreateContainer failed: QMP command failed: The device is not writable: Permission denied: unknown
``` 

But with `privileged_without_host_devices = true` I'm able to successfully run the same manifest.

```console
sudo -E kubectl get events --sort-by='.metadata.managedFields[0].time'
...
42s         Normal    Killing                   pod/nginx                   Stopping container nginx
25s         Normal    Scheduled                 pod/nginx                   Successfully assigned default/nginx to kata-gitlab-runner-2
19s         Normal    Pulling                   pod/nginx                   Pulling image "nginx"
18s         Normal    Pulled                    pod/nginx                   Successfully pulled image "nginx" in 1.582076725s
17s         Normal    Created                   pod/nginx                   Created container nginx
17s         Normal    Started                   pod/nginx                   Started container nginx
```

I'm unable to verify this behaviour with CRI-O 1.22 due to https://github.com/cri-o/cri-o/issues/5299.

**Comment by jclab-joseph** [comment] 2021-09-11 03:37
A new issue occurred after upgrading to Kata-containers 2.2.0.
https://github.com/kata-containers/kata-containers/issues/2611

@xinau Do you have containerd installed and running along with cri-o?

**Comment by xinau** [comment] 2021-09-13 06:19
@jclab-joseph I don't have containerd installed along with CRI-O. I'm not sure if this is the source, but I've manually installed with these lines

```bash
KATA_VERSION=2.2.0

# download and unpack kata containers release
curl -fsSL https://github.com/kata-containers/kata-containers/releases/download/${KATA_VERSION}/kata-static-${KATA_VERSION}-x86_64.tar.xz \
  | tar -xvJ --strip-components=2 -f -
  
# install kata containers at /opt/kata
sudo mv kata /opt

# make binaries available in $PATH
find /opt/kata/bin -name '*kata*' -exec sudo ln -s {} /usr/local/bin \;

# configure kata containers as a runtime in crio
cat << EOF | sudo tee /etc/crio/crio.conf
[crio.runtime.runtimes.kata]
  runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
  runtime_type = "vm"
  runtime_root = "/run/vc"
  privileged_without_host_devices = true
EOF
sudo systemctl restart crio
```

**Comment by jclab-joseph** [comment] 2021-09-13 07:38
@xinau Thank you.


Even after installing it according to his installation method, I still have the #2611 issue.
```
Warning  FailedCreatePodSandBox  2s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = dial unix /run/containerd/s/1f73980dff9c89bcf3bd31e0ba047860037a986eea96def0db92f9860c9c9e97: connect: connection refused

root     1034805  2.4  0.1 1253716 30180 ?       Sl   07:36   0:00 /usr/local/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 88f637d39512d83c9debe9d51cf73005b310d8634d576b8df6cddfec2a0571ac
root     1034966  4.2  0.1 1253716 31628 ?       Sl   07:36   0:00 /usr/local/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id 17c23dbfa62ce2ece619613af478fe927a08f7bc5b0a358cea6ecde03cc5a8b4
root     1035084  8.5  0.1 1253716 30464 ?       Sl   07:36   0:00 /usr/local/bin/containerd-shim-kata-v2 -namespace default -address  -publish-binary /usr/bin/crio -id fcdc60a20e90277da7dadccf6a98024b12761f3f94410493c7bfa3bb6804b872
```

**Comment by GabyCT** [comment] 2021-09-21 22:24
This issue is only see on Kata as with RunC is working fine
```
$ sudo ctr run --privileged --runtime io.containerd.runc.v2 -t quay.io/prometheus/busybox:latest test sh
/ # echo 100 > /proc/sys/vm/nr_hugepages
/ # cat /proc/sys/vm/nr_hugepages
100
```

**Comment by GabyCT** [comment] 2021-09-23 20:51
any idea @bergwolf ?

**Comment by GabyCT** [comment] 2021-09-24 19:03
Closing this issue as this is fixed with the latest version of containerd

**Comment by jclab-joseph** [comment] 2021-09-25 00:30
@GabyCT Is it really fixed? It doesn't even work with the latest containerd.

The method presented https://github.com/kata-containers/kata-containers/issues/2689#issuecomment-926685856 also does not work.

```
$ sudo sudo ctr run --privileged --runtime io.containerd.run.kata.v2 --mount type=bind,src=/dev,dst=/dev,options=rbind:rw -t --rm docker.io/library/busybox:latest hello sh
ctr: failed to create shim: QMP command failed: The device is not writable: Permission denied: unknown
$ sudo containerd --version
containerd github.com/containerd/containerd v1.5.5 72cec4be58a9eb6b2910f5d10f1c01ca47d231c0
```

```
Sep 25 00:27:41 microk8s-dev virtiofsd[1906784]: virtio_session_mount: Waiting for vhost-user socket connection...
Sep 25 00:27:41 microk8s-dev virtiofsd[1906784]: virtio_session_mount: Received vhost-user socket connection
Sep 25 00:27:41 microk8s-dev virtiofsd[1906795]: virtio_loop: Entry
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: fv_queue_set_started: qidx=0 started=1
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: fv_queue_set_started: qidx=1 started=1
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: fv_queue_thread: Start for queue 0 kick_fd 9
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: fv_queue_thread: Start for queue 1 kick_fd 12
Sep 25 00:27:42 microk8s-dev kata[1906775]: time="2021-09-25T00:27:42.336954223Z" level=error msg="container create failed" error="QMP command failed: The device is not writable: Permission denied" name=containerd-shim-v2 pid=1906775 sandbox=hello source=virtcontainers subsystem=container
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.336954223Z" level=error msg="container create failed" error="QMP command failed: The device is not writable: Permission denied" name=containerd-shim-v2 pid=1906775 sandbox=hello source=virtcontainers subsystem=container
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.337098809Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1906775 rootfs-dir=/run/kata-containers/shared/sandboxes/hello/mounts/hello/rootfs sandbox=hello source=virtcontainers subsystem=mount
Sep 25 00:27:42 microk8s-dev kata[1906775]: time="2021-09-25T00:27:42.337098809Z" level=warning error="no such file or directory" name=containerd-shim-v2 pid=1906775 rootfs-dir=/run/kata-containers/shared/sandboxes/hello/mounts/hello/rootfs sandbox=hello source=virtcontainers subsystem=mount
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: virtio_loop: ppoll interrupted, going around
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: virtio_loop: Stopping queue 0 thread
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: fv_queue_thread: kill event on queue 0 - quitting
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: virtio_loop: Stopping queue 1 thread
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: fv_queue_thread: kill event on queue 1 - quitting
Sep 25 00:27:42 microk8s-dev virtiofsd[1906795]: virtio_loop: Exit
Sep 25 00:27:42 microk8s-dev kata[1906775]: time="2021-09-25T00:27:42.340947325Z" level=warning msg="sandbox cgroups path is empty" name=containerd-shim-v2 pid=1906775 sandbox=hello source=virtcontainers subsystem=sandbox
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.340947325Z" level=warning msg="sandbox cgroups path is empty" name=containerd-shim-v2 pid=1906775 sandbox=hello source=virtcontainers subsystem=sandbox
Sep 25 00:27:42 microk8s-dev kata[1906775]: time="2021-09-25T00:27:42.341557156Z" level=warning msg="failed to cleanup netns" error="failed to get netns /var/run/netns/cnitest-8e3cc519-0ed4-6b88-bd55-c45e6ee94231: failed to Statfs \"/var/run/netns/cnitest-8e3cc519-0ed4-6b88-bd55-c45e6ee94231\": no such file or directory" name=containerd-shim-v2 path=/var/run/netns/cnitest-8e3cc519-0ed4-6b88-bd55-c45e6ee94231 pid=1906775 sandbox=hello source=katautils
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.341557156Z" level=warning msg="failed to cleanup netns" error="failed to get netns /var/run/netns/cnitest-8e3cc519-0ed4-6b88-bd55-c45e6ee94231: failed to Statfs \"/var/run/netns/cnitest-8e3cc519-0ed4-6b88-bd55-c45e6ee94231\": no such file or directory" name=containerd-shim-v2 path=/var/run/netns/cnitest-8e3cc519-0ed4-6b88-bd55-c45e6ee94231 pid=1906775 sandbox=hello source=katautils
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.347672210Z" level=info msg="shim disconnected" id=hello
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.347960539Z" level=warning msg="cleaning up after shim disconnected" id=hello namespace=default
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.347987509Z" level=info msg="cleaning up dead shim"
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.377443480Z" level=error msg="failed to delete" cmd="/usr/local/bin/containerd-shim-kata-v2 -namespace default -address /run/containerd/containerd.sock -publish-binary /usr/local/bin/containerd -id hello -bundle /run/containerd/io.containerd.runtime.v2.task/default/hello delete" error="exit status 1"
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.377498357Z" level=warning msg="failed to clean up after shim disconnected" error="time=\"2021-09-25T00:27:42Z\" level=warning msg=\"failed to cleanup container\" container=hello error=\"open /run/vc/sbs/hello: no such file or directory\" name=containerd-shim-v2 pid=1906807 sandbox=hello source=containerd-kata-shim-v2\nio.containerd.kata.v2: open /run/vc/sbs/hello: no such file or directory\n: exit status 1" id=hello namespace=default
Sep 25 00:27:42 microk8s-dev containerd[1896103]: time="2021-09-25T00:27:42.377555538Z" level=error msg="copy shim log" error="read /proc/self/fd/19: file already closed"
```

**Comment by xinau** [comment] 2021-10-04 08:23
@GabyCT This issue is definitly not closed with the lastest containerd (1.5.6) version. Could you please re-open this issue or is this tracked somewhere else?

```console
$ sudo sudo ctr run --privileged --runtime io.containerd.run.kata.v2 --mount type=bind,src=/dev,dst=/dev,options=rbind:rw -t --rm docker.io/library/busybox:latest hello sh
ctr: failed to create shim: QMP command failed: The device is not writable: Permission denied: unknown
$ sudo sudo ctr run --privileged --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh
ctr: failed to create shim: QMP command failed: The device is not writable: Permission denied: unknown
$ sudo ctr run --privileged --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh
ctr: failed to create shim: QMP command failed: The device is not writable: Permission denied: unknown
$ sudo ctr run --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/busybox:latest hello sh
/ #
$ sudo ctr version
Client:
  Version:  v1.5.6
  Revision: 1a1b383ad5b520349f13f9715e0cd1e2f132c087
  Go version: go1.16.8

Server:
  Version:  v1.5.6
  Revision: 1a1b383ad5b520349f13f9715e0cd1e2f132c087
  UUID: 5bd24cf7-3c49-4ded-873b-d09b650125dc
$ cat /etc/containerd/config.toml
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
SystemdCgroup = true

[plugins.cri.containerd.runtimes.kata]
runtime_type = "io.containerd.kata.v2"
privileged_without_host_devices = true
```

**Comment by devimc** [comment] 2021-10-04 12:49
@xinau what the output of: `sudo losetup` ?

**Comment by jclab-joseph** [comment] 2021-10-04 13:22
```
NAME SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                         DIO LOG-SEC
/dev/loop1
             0      0         1  1 /var/lib/snapd/snaps/core18_2128.snap
                                                                       0     512
/dev/loop8
             0      0         1  1 /var/lib/snapd/snaps/snapd_12883.snap
                                                                       0     512
/dev/loop6
             0      0         1  1 /var/lib/snapd/snaps/core20_1081.snap
                                                                       0     512
/dev/loop4
             0      0         1  1 /var/lib/snapd/snaps/snapd_13170.snap
                                                                       0     512
/dev/loop2
             0      0         1  1 /var/lib/snapd/snaps/lxd_21545.snap
                                                                       0     512
/dev/loop0
             0      0         1  1 /var/lib/snapd/snaps/core18_1944.snap
                                                                       0     512
/dev/loop9
             0      0         1  1 /var/lib/snapd/snaps/kata-containers_946.snap
                                                                       0     512
/dev/loop7
             0      0         1  1 /var/lib/snapd/snaps/kata-containers_1036.snap
                                                                       0     512
/dev/loop3
             0      0         1  1 /var/lib/snapd/snaps/lxd_21029.snap
                                                                       0     512
```

**Comment by devimc** [comment] 2021-10-20 20:27
@jclab-joseph agree, but there is a limit in the amount of devices that you can attach to Kata Containers (VM)

**Comment by liubin** [comment] 2022-09-26 08:12
Both ctr and nerdctl now support skip passing host devices to guest, the latest ctr/nerdctl will not affect by this error.

- nerdctl

From: v0.23.0

PR: https://github.com/containerd/nerdctl/pull/1291

- ctr

From: not released yet, you need to build from the source.
PR: https://github.com/containerd/containerd/pull/7328

**Closed by liubin** 2022-09-26 08:12 UTC
Labels: bug, area/QEMU
