### ISSUE TITLE
runtime-rs: implement direct volume handler for kata-ctl

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [kata-containers/kata-containers#5369] opened 2022-10-07 06:30 UTC
implement direct volume handler (volume stat and volume add) with unit test for kata-ctl

**Comment by jodh-intel** [comment] 2022-10-07 08:39
This is a duplicate of #5341.

**Comment by Tim-0731-Hzt** [comment] 2022-10-07 11:14
Same as #5370

**Comment by Tim-0731-Hzt** [comment] 2022-10-15 02:47
Yes! 
1. There are four operations in direct volume(`add`, `remove`, `stat`, `resize`). To handle `stat` and `resize`, you can see https://github.com/kata-containers/kata-containers/blob/main/src/runtime/pkg/containerd-shim-v2/shim_management.go#L266-L267, and this could be implemented in `runtime-rs/crates/runtimes/src/shim_mgmt`.  To handle `add`, see https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/container.go#L615.
2. `runtime/cmd/kata-runtime/kata-volume.go` and `runtime/pkg/direct-volume` is reference to #5341, which is used for sending the direct volume operations intead of handling.

**Comment by tzY15368** [comment] 2022-10-17 01:24
@Tim-0731-Hzt  Thinks for the info! It looks like runtime-rs's version of sandbox doesn't support stat queries yet, nor does the agent have such a trait in `runtime-rs/crates/agent/src/libs.rs` for runtime-rs to directly call. I'm wondering if I missed something🤔

**Comment by Tim-0731-Hzt** [comment] 2022-10-17 03:45
> @Tim-0731-Hzt Thanks for the info! It looks like runtime-rs's version of sandbox doesn't support direct-volume stat queries or resize yet, nor does the agent have such a trait in `runtime-rs/crates/agent/src/libs.rs` for runtime-rs to directly call. I'm wondering if I missed something🤔

Hi @tzY15368 . Yes, currently, runtime-rs doesn't support these functionalities, I think you need to define the trait and implement it.

**Comment by tzY15368** [comment] 2022-10-25 22:24
@Tim-0731-Hzt Hi Tim, I've implemented the runtime-rs and sandbox part of this issue, and just realized that `resize_volume` isn't implemented in the agent either, so I looked back at the old agent repo https://github.dev/kata-containers/agent trying to find what this command actually did, but didn't really find much relevant info. Could you share some insight on this?

**Comment by Tim-0731-Hzt** [comment] 2022-10-26 01:30
Hi @tzY15368. I just found this issue #3694, you are right, It's not implemented yet. I will change this issue to implement the `volume stat` only.

**Comment by tzY15368** [comment] 2022-10-26 02:02
> Hi @tzY15368. I just found this issue #3694, you are right, It's not implemented yet. I will change this issue to implement the `volume stat` and `volume add`. But `volume add` depends on block device hot plug #5441, I think you can left this until it is merged.

Thanks for the info! The `volume add` command took reference from [runtime-go](https://github.com/kata-containers/kata-containers/blob/cd27ad144e1a111cb606015c5c9671431535e644/src/runtime/pkg/direct-volume/utils.go#L57-L79), which was called directly from `kata-runtime` binary and didn't really interact with the runtime module through any form of RPC, I think I missed something in the big picture or perhaps the design was changed?

**Comment by tzY15368** [comment] 2022-10-26 02:08
> Hi @tzY15368. I just found this issue #3694, you are right, It's not implemented yet. I will change this issue to implement the `volume stat` and `volume add`. But `volume add` depends on block device hot plug #5441, I think you can left this until it is merged.

Since everything's ready right down to the agent layer at this point, maybe I can have a try on #3694 as well?

**Comment by Tim-0731-Hzt** [comment] 2022-10-26 02:24
https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/container.go#L615 
I think you can go through this. When you do `add`, you will write the mount info into a json file, and the function in this link will read the file to get the info, and then it will follow the steps of handling volume.

**Comment by Tim-0731-Hzt** [comment] 2022-10-26 02:29
> > Hi @tzY15368. I just found this issue #3694, you are right, It's not implemented yet. I will change this issue to implement the `volume stat` and `volume add`. But `volume add` depends on block device hot plug #5441, I think you can left this until it is merged.
> 
> Also, since everything's ready right down to the agent layer at this point, maybe I can have a try on #3694 as well? The docs seem to be in [docs](https://github.com/kata-containers/kata-containers/blob/main/docs/design/direct-blk-device-assignment.md), not sure how hard it would be to call qemu functions (or dragonball?) tho.

ye, I think you can reply this issue. Seems it is assigned to @fengwang666 currently.

**Closed** 2023-03-13 07:58 UTC
Labels: runtime-rs, kata-ctl
