### ISSUE TITLE
Java Applications not supported?

### ISSUE THREAD

**Issue by lestich** [kata-containers/kata-containers#564] opened 2020-08-24 15:04 UTC
# Description of problem

I cannot start Springboot-Applications inside Kata Containers
Default Config and very simple Benchmarking app which checks Prime Numbers

# Expected result
running Kata Containers

# Actual result

library initialization failed - unable to allocate file descriptor table - out of memory

The same occured when i was trying to run the google microservice demo (https://github.com/GoogleCloudPlatform/microservices-demo) Everything was running except for java applications

Any ideas?

**Comment by devimc** [comment] 2020-08-24 15:11
you need more memory, try increasing `default_memory` in the configuration file (`/usr/share/defaults/kata-containers/configuration.toml`), or in the command line if you are using docker/podman (-m 6G)

**Comment by bluecodefish** [comment] 2020-08-24 15:18
Memory is set to 8G and 4 CPUs

**Comment by devimc** [comment] 2020-08-24 15:27
duplicate of https://github.com/kata-containers/runtime/issues/2597

**Comment by todaygood** [comment] 2021-03-10 11:22
I met the same issue , and  found the issue still exists after I changed  default_memory=8G in the configuration file (/usr/share/defaults/kata-containers/configuration.toml)

how to solve?

**Comment by huisebug** [comment] 2021-05-24 03:01
Currently all kata runtimes, and the versions are all 1.11+
After my test, the number of open files is too large, which makes java unable to run.
Cannot run when the image is FROM alpine,
It can run when the image is FROM slim,
For docker installed on Centos8 system, the default number of open files for all containers is 1048576
For docker installed on Centos7 system, the number of open files for all containers is 1073741816 by default
And the docker version is the latest 20.10.6

Solution:
Method 1, do not use the docker image based on the alpine-based image. Obviously, when the number of open files is too large, the alpine under kata will run incorrectly. Many services are run by alpine, this method is not recommended
Method 2, when using kata to run, use centos8 to run docker instead of centos7. This is the recommended method, but you need to re-operate the system
Method 3, you can add dockerd startup parameters to the docker system service file
--default-ulimit nofile=65535:65535 Set the number of open files for all containers. This is the recommended method.
Setting LimitNOFILE=65535 is invalid and will not change the number of open files in all docker containers.

**Closed** 2022-05-27 01:21 UTC
Labels: duplicate
