### ISSUE TITLE
clh CI is failing `Copy from pod to host` test

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/kata-containers#1227] opened 2021-01-05 06:32 UTC
It is failing a lot on different PRs:

```
04:56:16 ok 1 Copy file in a pod
04:56:18 not ok 2 Copy from pod to host
04:56:18 # (in test file k8s-copy-file.bats, line 47)
04:56:18 #   `kubectl cp "$pod_name":/tmp/"$file_name" "$file_name"' failed
04:56:18 # INFO: k8s configured to use runtimeclass
```

The oldest one is http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/539/ but it must happen even before that and we have dropped older archives.

**Comment by bergwolf** [comment] 2021-01-05 06:37
I've dropped `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0` from `required` CI list so that it doesn't block other unrelated PRs. Let's fix the issue before re-adding it there.

**Comment by bergwolf** [comment] 2021-01-05 06:42
@likebreath do you have time to look into it? Since it only happens on clh, my gut feeling is that it might relate to clh working with virtiofs.

**Comment by fidencio** [comment] 2021-01-05 07:29
I've also reported this as https://github.com/kata-containers/tests/issues/3061

**Comment by likebreath** [comment] 2021-01-05 22:41
@bergwolf @fidencio Thanks for reporting the issues. I am now fully occupied and won't have cycles to debug it. Sorry about that.

Luckily @chavafg was already on it https://github.com/kata-containers/tests/issues/3061#issuecomment-748394447. Given the tests is failing randomly, I agree that the virtiofs is likely to be related to the issue. /cc @jcvenegas

**Comment by chavafg** [comment] 2021-01-06 05:29
@bergwolf @fidencio, I tried to reproduce the issue locally without any luck. But I modified the test in https://github.com/kata-containers/tests/pull/3131, basically to use another pod spec. With this change, the test passes correctly and is no longer flaky.

If you agree that this could be a valid workaround that we could use while the issue is investigated, we can merge the change.

**Comment by bergwolf** [comment] 2021-01-06 07:27
@chavafg thanks for looking into it. I totally agree we can use it as we workaround. If it is just relating to specific image, it can be debugged separately.

**Comment by likebreath** [comment] 2021-01-27 00:29
This issue was fixed by @chavafg in https://github.com/kata-containers/tests/pull/3131. Closing it. Thank you.

**Closed by likebreath** 2021-01-27 00:29 UTC
Labels: bug, needs-review
