### ISSUE TITLE
kata-ctl: exec command does not expand short container ID

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/kata-containers#9189] opened 2024-02-29 09:49 UTC
```bash
$ docker ps
CONTAINER ID   IMAGE                               COMMAND   CREATED          STATUS          PORTS     NAMES
6ad48f11de26   quay.io/prometheus/busybox:latest   "sh"      14 minutes ago   Up 14 minutes             objective_neumann

$  docker ps --no-trunc
CONTAINER ID                                                       IMAGE                               COMMAND   CREATED          STATUS          PORTS     NAMES
6ad48f11de26d151915672b72fb692a1b485df2b3a6334f419bec1cb336f1ffc   quay.io/prometheus/busybox:latest   "sh"      14 minutes ago   Up 14 minutes             objective_neumann

# ERROR: Connecting with the short name fails
$ sudo kata-ctl exec 6ad48f11de26
subsystem: kata-ctl_main
 Feb 29 09:46:41.788 ERRO Error {
    context: "get debug console socket URL",
    source: Error {
        context: "get connection vsock",
        source: hyper::Error(
            Connect,
            Os {
                code: 2,
                kind: NotFound,
                message: "No such file or directory",
            },
        ),
    },
}

# OK: But connecting with the long or full name works
$ sudo kata-ctl exec 6ad48f11de26d151915672b72fb692a1b485df2b3a6334f419bec1cb336f1ffc
root@localhost:/#
```

**Comment by Apokleos** [comment] 2024-02-29 11:03
Hi, James @jodh-intel Is anyone working on this? If not, I can claim the issue and fix it. I recently experienced the inconvenience caused by the full ID.

**Comment by jodh-intel** [comment] 2024-02-29 11:54
Hi @Apokleos - please feel free to take it :smile:

**Comment by Apokleos** [comment] 2024-02-29 12:01
Ok @jodh-intel I assign it myself.

**Closed** 2024-03-07 11:26 UTC
Labels: bug, good-first-issue, lang/rust, kata-ctl
