### ISSUE TITLE
kata-qemu-tdx fails to mount volume bigger than 256M

### ISSUE THREAD

**Issue by JakubLedworowski** [kata-containers/kata-containers#10264] opened 2024-09-05 11:58 UTC
# Description of problem

1. Prepare Intel platform with TDX enabled and kubernetes cluster
2. Install nydus-snapshotter v0.13.14 to the cluster
3. Install kata-containers with kata-qemu and kata-qemu-tdx runtime classes v3.8.0
4. Prepare the following directories and files on worker node:

  ```
  mkdir -p /tmp/nydus-mnt-test-empty
  mkdir /tmp/nydus-mnt-test && cd /tmp/nydus-mnt-test
  dd if=/dev/zero of=big-file-256M.img bs=256M count=1
  dd if=/dev/zero of=big-file-512M.img bs=512M count=1
  ```
5. Prepare the following pod definitions as `dummy-repro-base.yaml`:

```dummy-repro-base.yaml
apiVersion: v1
kind: Pod
metadata:
  name: dummy-repro-base-empty
spec:
  runtimeClassName: kata-qemu-tdx
  containers:
    - name: dummy
      image: storytel/alpine-bash-curl:latest
      imagePullPolicy: Always
      command: [ "/bin/sh","-c" ]
      args:
        - |
          while :; do echo '.'; sleep 5 ; done
      resources:
        limits:
          memory: "2Gi"
      volumeMounts:
        - mountPath: /data
          name: tmp-volume-empty
  volumes:
    - name: tmp-volume-empty
      hostPath:
        path: /tmp/nydus-mnt-test-empty
        type: Directory
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-repro-base-256m
spec:
  runtimeClassName: kata-qemu-tdx
  containers:
    - name: dummy
      image: storytel/alpine-bash-curl:latest
      imagePullPolicy: Always
      command: [ "/bin/sh","-c" ]
      args:
        - |
          while :; do echo '.'; sleep 5 ; done
      resources:
        limits:
          memory: "2Gi"
      volumeMounts:
        - mountPath: /data
          name: tmp-volume
  volumes:
    - name: tmp-volume
      hostPath:
        path: /tmp/nydus-mnt-test/big-file-256M.img
        type: File
---
apiVersion: v1
kind: Pod
metadata:
  name: dummy-repro-base-512m
spec:
  runtimeClassName: kata-qemu-tdx
  containers:
    - name: dummy
      image: storytel/alpine-bash-curl:latest
      imagePullPolicy: Always
      command: [ "/bin/sh","-c" ]
      args:
        - |
          while :; do echo '.'; sleep 5 ; done
      resources:
        limits:
          memory: "4Gi"
      volumeMounts:
        - mountPath: /data
          name: tmp-volume
  volumes:
    - name: tmp-volume
      hostPath:
        path: /tmp/nydus-mnt-test/big-file-512M.img
        type: File
```

6. Deploy: 
`kubectl apply -f dummy-repro-base.yaml`

# Expected result

Get pods:
`kubectl get pods | grep -i dummy`

All pods are running:
```
dummy-repro-base-256m    1/1     Running
dummy-repro-base-512m    1/1     Running
dummy-repro-base-empty   1/1     Running
```

# Actual result

One of the pods that mounts the 512M file is failing to start:
```
dummy-repro-base-256m    1/1     Running
dummy-repro-base-512m    0/1     RunContainerError
dummy-repro-base-empty   1/1     Running
```

Errors show up in events for `pod/dummy-repro-base-512m`:
```
kubectl events --for='pod/dummy-repro-base-512m' | tail -n 4
3m11s (x4 over 9m56s)   Normal    Created     Pod/dummy-repro-base-512m   Created container dummy
3m11s                   Normal    Pulled      Pod/dummy-repro-base-512m   Successfully pulled image "storytel/alpine-bash-curl:latest" in 625ms (625ms including waiting). Image size: 6089404 bytes.
71s (x4 over 7m56s)     Warning   Failed      Pod/dummy-repro-base-512m   Error: context deadline exceeded
33s (x8 over 5m55s)     Warning   BackOff     Pod/dummy-repro-base-512m   Back-off restarting failed container dummy in pod dummy-repro-base-512m_default(e9abbf26-c16d-45dd-9f3f-3c1b5df31160)
```

No error in events for `pod/dummy-repro-base-256m`:
```
kubectl events --for='pod/dummy-repro-base-256m' | tail -n 4
9m28s       Normal   Pulling     Pod/dummy-repro-base-256m   Pulling image "storytel/alpine-bash-curl:latest"
9m27s       Normal   Pulled      Pod/dummy-repro-base-256m   Successfully pulled image "storytel/alpine-bash-curl:latest" in 635ms (635ms including waiting). Image size: 6089404 bytes.
9m27s       Normal   Created     Pod/dummy-repro-base-256m   Created container dummy
7m51s       Normal   Started     Pod/dummy-repro-base-256m   Started container dummy
```

# Further information

If runtime class name is changed to `kata-qemu` (nydus is not used) all pods are starting.

Kata-deploy image: quay.io/fidencio/kata-containers:3.8.0-with-ita-v0.0.1
Image comes from this branch: https://github.com/fidencio/kata-containers/tree/intel/3.8.0-with-ita
Commit: [b4811d0c](https://github.com/fidencio/kata-containers/commit/b4811d0c0d62a7093ce869fda2c16909d784406b)
Tested host OS: Ubuntu 24.04
Kernel: 6.8.0

**Comment by fidencio** [comment] 2024-09-05 12:08
cc @ChengyuZhu6

**Comment by ChengyuZhu6** [comment] 2024-09-05 12:16
@JakubLedworowski  @fidencio I don’t think it’s related to nydus or guest pull. Could the issue be a timeout with the `CopyFile` request in qemu-tdx?

**Comment by ChengyuZhu6** [comment] 2024-09-05 12:19
Could you provide detailed debug logs of kata? @JakubLedworowski

**Comment by ChengyuZhu6** [comment] 2024-09-05 13:11
https://github.com/kata-containers/kata-containers/pull/9332

**Comment by ChengyuZhu6** [comment] 2024-09-05 13:49
It's maybe caused by the timeout of `CreateContainerRequest`. You can increase the `create_container_timeout`: https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md#:~:text=io.katacontainers.config.runtime.create_container_timeout, https://github.com/kata-containers/kata-containers/blob/70491ff29f3b1c1a28fc8b73ec1b7e9b1ab6da37/src/runtime/config/configuration-qemu-tdx.toml.in#L663-L669

**Comment by ChengyuZhu6** [comment] 2024-09-05 13:53
I’ll close the issue because it can be resolved using the methods mentioned above. @JakubLedworowski @fidencio

**Closed by ChengyuZhu6** 2024-09-05 13:53 UTC
Labels: bug, needs-review
