### ISSUE TITLE
kata-qemu-tdx fails to bind grpc to unix socket

### ISSUE THREAD

**Issue by JakubLedworowski** [kata-containers/kata-containers#10048] opened 2024-07-19 13:36 UTC
# Description of problem

1. Prepare Intel platform with TDX enabled
2. Install kata-qemu and kata-qemu-tdx runtime classes
3. Create simple application that binds GRPC to unix socket, you may use the pre-built image:

```myapp.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-deployment
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec:
      runtimeClassName: kata-qemu-tdx
      hostIPC: true
      containers:
      - name: myapp-deployment
        image: quay.io/jakub_ledworowski/kata-containers-issue/grpc-test:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
```

[OPTIONAL] The server code in the image is below, if you'd like to build it yourself (the file is also attached to this issue):
```main.go
package main

import (
    "log"
    "net"
    "os"
    "os/signal"
    "syscall"

    "google.golang.org/grpc"
    "google.golang.org/grpc/health"
    "google.golang.org/grpc/health/grpc_health_v1"
    "google.golang.org/grpc/reflection"
)

const (
    socketPath = "/tmp/text-generation-server-0" // Path to the Unix socket
)

func main() {
    // Listen on the Unix socket
    listener, err := net.Listen("unix", socketPath)
    if err != nil {
        log.Fatalf("Failed to listen: %v", err)
    }

    // Setup a channel to listen for interrupt or terminate signals
    // to perform cleanup before exiting
    signals := make(chan os.Signal, 1)
    signal.Notify(signals, os.Interrupt, syscall.SIGTERM)
    go func() {
        <-signals
        os.Remove(socketPath) // Remove the socket file
        os.Exit(1)
    }()

    // Create a new gRPC server
    server := grpc.NewServer()

    // Register health service
    grpc_health_v1.RegisterHealthServer(server, health.NewServer())

    // Register reflection service on gRPC server
    reflection.Register(server)

    // Log that the server is running and serve requests
    log.Printf("gRPC server running on Unix socket %s", socketPath)
    if err := server.Serve(listener); err != nil {
        log.Fatalf("Failed to serve: %v", err)
    }
}
```

4. Deploy:
`kubectl apply -f myapp.yaml`

# Expected result

Pod is started.

# Actual result

Pod fails to start because it cannot bind the socket.

Logs of the pod show error:
`Failed to listen: listen unix /tmp/text-generation-server-0: bind: no such device or address`

# Further information

If in myapp.yaml the runtimeClassName is changed from `kata-qemu-tdx` to `kata-qemu` the socket is bound correctly:

`gRPC server running on Unix socket /tmp/text-generation-server-0`

Attaching the Dockerfile, myapp.yaml, main.go, go.mod and go.sum:
[myapp.zip](https://github.com/user-attachments/files/16361968/myapp.zip)

Tested host OS: Ubuntu 24.04
Kernel: 6.8.0

**Comment by JakubLedworowski** [comment] 2024-07-22 10:06
> @JakubLedworowski which version of CoCo?
> 
> cc: @fidencio

No CoCo here, only kata. 

Image: quay.io/fidencio/kata-containers:idc-sdp-cloud-v0.0.3
Image comes from this branch: https://github.com/fidencio/kata-containers/commits/intel/idc-sdp-cloud/
Commit: 4e31ed46d90a375de2255150de11182dd410e344

**Comment by fidencio** [comment] 2024-07-24 14:41
@JakubLedworowski, there's another thing crossing my mind right now: virtio-9p.
 
If you tested with the default kata-qemu runtimeclass, that means you were using virtio-fs there instead of 9p, and that may be the reason you didn't hit the issue
Would it be possible to change the shared_fs to virtio-9p with the kata-qemu configuration file and retry? At least we'll be able to narrow down which component may be causing the issue.

**Comment by fidencio** [comment] 2024-07-24 15:06
Testing with the `kata-qemu` from main, and here's the results when using:
* shared_fs = virtio-9p:
```
$ kubectl logs myapp-deployment-75758b9584-p4x8t
2024/07/24 15:03:00 Failed to listen: listen unix /tmp/text-generation-server-0: bind: no such device or address
```

* shared_fs = virtio-fs:
```
$ kubectl logs myapp-deployment-75758b9584-xmm9h
2024/07/24 15:01:05 gRPC server running on Unix socket /tmp/text-generation-server-
```

This means the culprit of the issue is virtio-9p not behaving well.
I'll rebase the code you're using atop of main, as that includes fixes for the nydus-snapshotter, then we can switch to using `shared_fs = none`, and you'll be good to go.

However, as the rebase itself and what you'll be using is more related to how we do things internally at Intel than upstream, I'll close the issue.

Thanks a lot for the very good report, which helped me test it in a very easy and simple way. <3

**Closed by fidencio** 2024-07-24 15:06 UTC
Labels: bug, needs-review
