### ISSUE TITLE
CCv0: kata container doesn't have networking

### ISSUE THREAD

**Issue by immersommer** [kata-containers/kata-containers#7019] opened 2023-06-01 22:52 UTC
# Question Description
When I run the kata container with the command `sudo ctr run --cni --runtime io.containerd.run.kata.v2 -t --rm docker.io/library/ubuntu:20.04 test-ubuntu sh` , the running container has no network inside it.
![image](https://github.com/kata-containers/kata-containers/assets/77921310/d210f860-2fa0-40c1-830a-8684695c8b31)
Does anyone know how to fix this problem?
# Expected Result
The container owns the network and can do updates.
# Current Result
The qemu doesn't have -netdev setting. But cni0 and veth are in UP state.
## qemu
 `$ ps aux | grep qemu | grep device`
![image](https://github.com/kata-containers/kata-containers/assets/77921310/793fa172-4f17-4e82-9818-4e58392ac3c7)

## network on host
`$ ip a`
![image](https://github.com/kata-containers/kata-containers/assets/77921310/4c9ea800-ac55-4f4f-9381-54bc0594a798)
# Configuration 
## contained configuration
```
[debug]
  level = "debug"
[plugins]
  [plugins.cri]
    disable_hugetlb_controller = false
    [plugins.cri.containerd]
      [plugins.cri.containerd.runtimes]
        [plugins.cri.containerd.runtimes.runc]
           runtime_type = "io.containerd.runc.v2"
           [plugins.cri.containerd.runtimes.runc.options]
             BinaryName = "/usr/local/sbin/runc"
             Root = ""
        [plugins.cri.containerd.runtimes.kata]
           runtime_type = "io.containerd.kata.v2"
           pod_annotations = ["io.katacontainers.*"]
           privileged_without_host_devices = true
           [plugins.cri.containerd.runtimes.kata.options]
             ConfigPath = "/usr/share/defaults/kata-containers/configuration-qemu.toml"
    [plugins.cri.registry.mirrors."localhost:5000"]
      endpoint = ["http://localhost:5000"]
    [plugins.cri.cni]
      conf_dir = "/etc/cni/net.d"
```
## /etc/cni/net.d/10-mynet.conf
```
{
        "cniVersion": "0.2.0",
        "name": "mynet",
        "type": "bridge",
        "bridge": "cni0",
        "isGateway": true,
        "ipMasq": true,
        "ipam": {
                "type": "host-local",
                "subnet": "10.88.0.1/16",
                "routes": [
                        { "dst": "0.0.0.0/0" }
                ]
        }
}
```
## kata configuration.toml
```
# Copyright (c) 2017-2019 Intel Corporation
# Copyright (c) 2021 Adobe Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# XXX: WARNING: this file is auto-generated.
# XXX:
# XXX: Source file: "config/configuration-qemu.toml.in"
# XXX: Project:
# XXX:   Name: Kata Containers
# XXX:   Type: kata

[hypervisor.qemu]
path = "/home/ziyi/kata-containers/build/opt/confidential-containers/bin/qemu-system-x86_64"
kernel = "/usr/share/kata-containers/vmlinuz-snp.container"
#image = "/usr/share/kata-containers/kata-containers.img"
initrd = "/usr/share/kata-containers/kata-containers-initrd.img"
machine_type = "q35"

# rootfs filesystem type:
#   - ext4 (default)
#   - xfs
#   - erofs
rootfs_type="ext4"

# Enable confidential guest support.
# Toggling that setting may trigger different hardware features, ranging
# from memory encryption to both memory and CPU-state encryption and integrity.
# The Kata Containers runtime dynamically detects the available feature set and
# aims at enabling the largest possible one, returning an error if none is
# available, or none is supported by the hypervisor.
#
# Known limitations:
# * Does not work by design:
#   - CPU Hotplug 
#   - Memory Hotplug
#   - NVDIMM devices
#
# Default false
confidential_guest = true

# Enable pre-attestation for AMD SEV and SEV-ES guests.
# Applies only if confidential_guest is true.
# (default: false)
#guest_pre_attestation = true
#
# A remote key broker server (KBS) is required to validate the attestation
# measurement and inject a secret key.  
# See https://github.com/confidential-containers/simple-kbs
#guest_pre_attestation_kbs_uri = "localhost:44444"
#
# The simple-kbs can be run in "online" and "offline" modes
#guest_pre_attestation_kbs_mode="online" 
#
# Keyset ID of the injected secret (offline kbs)
#guest_pre_attestation_keyset = "KEYSET-1"
#
# SEV guest policy
#sev_guest_policy = 3

# SEV certificate chain path 
#sev_cert_chain="/home/cert_chain.cert"

# Choose AMD SEV-SNP confidential guests
# In case of using confidential guests on AMD hardware that supports both SEV
# and SEV-SNP, the following enables SEV-SNP guests. SEV guests are default.
# Default false
sev_snp_guest = false

# SNP guest policy
# Refer SEV Secure Nested Paging Firmware ABI Specification (sectin 4.3) to
# change this value.
# unspecified or == 0  -->  0x30000 i.e. Bit#17 is '1' and Bit#16 is '1' (SMT is allowed)
# snp_guest_policy=0x30000

# Enable running QEMU VMM as a non-root user.
# By default QEMU VMM run as root. When this is set to true, QEMU VMM process runs as
# a non-root random user. See documentation for the limitations of this mode.
# rootless = true

# List of valid annotation names for the hypervisor
# Each member of the list is a regular expression, which is the base name
# of the annotation, e.g. "path" for io.katacontainers.config.hypervisor.path"
enable_annotations = ["enable_iommu"]

# List of valid annotations values for the hypervisor
# Each member of the list is a path pattern as described by glob(3).
# The default if not set is empty (all annotations rejected.)
# Your distribution recommends: ["/usr/bin/qemu-system-x86_64"]
valid_hypervisor_paths = ["/usr/bin/qemu-system-x86_64"]

# Optional space-separated list of options to pass to the guest kernel.
# For example, use `kernel_params = "vsyscall=emulate"` if you are having
# trouble running pre-2.15 glibc.
#
# WARNING: - any parameter specified here will take priority over the default
# parameter value of the same name used to start the virtual machine.
# Do not set values here unless you understand the impact of doing so as you
# may stop the virtual machine from booting.
# To see the list of default parameters, enable hypervisor debug, create a
# container and look for 'default-kernel-parameters' log entries.
kernel_params = "  agent.enable_signature_verification=false  agent.log=debug agent.debug_console"

# Path to the firmware.
# If you want that qemu uses the default firmware leave this option empty
firmware = "/home/ziyi/kata-containers/build/opt/confidential-containers/share/ovmf/AMDSEV.fd"

# Path to the firmware volume.
# firmware TDVF or OVMF can be split into FIRMWARE_VARS.fd (UEFI variables
# as configuration) and FIRMWARE_CODE.fd (UEFI program image). UEFI variables
# can be customized per each user while UEFI code is kept same.
firmware_volume = ""

......

[netmon]
path = "/opt/kata/libexec/kata-containers/kata-netmon"
enable_netmon = true
enable_debug = true

[runtime]
# If enabled, the runtime will log additional debug messages to the
# system log
# (default: disabled)
enable_debug = true
#
# Internetworking model
# Determines how the VM should be connected to the
# the container network interface
# Options:
#
#   - macvtap
#     Used when the Container network interface can be bridged using
#     macvtap.
#
#   - none
#     Used when customize network. Only creates a tap device. No veth pair.
#
#   - tcfilter
#     Uses tc filter rules to redirect traffic from the network interface
#     provided by plugin to a tap interface connected to the VM.
#
#internetworking_model="tcfilter"
internetworking_model="macvtap"

# disable guest seccomp
# Determines whether container seccomp profiles are passed to the virtual
# machine and applied by the kata agent. If set to true, seccomp is not applied
# within the guest
# (default: true)
disable_guest_seccomp=true
......
```

**Comment by jepio** [comment] 2023-06-02 16:07
I've started investigating. So far I see that

`func (n *LinuxNetwork) addAllEndpoints(ctx context.Context, s *Sandbox, hotplug bool) error {`

does an early exit because this condition is true.

`if len(netInfo.Addrs) == 0 {`

**Comment by jepio** [comment] 2023-06-06 10:48
So upon investigating - this is a duplicate of https://github.com/kata-containers/kata-containers/issues/2580. Ctr runs CNI after the sandbox is created and doesn't pass a network namespace to the runtime (instead the runtime creates its own, that's why it's called `cnitest-xxxxx`).

This is still not resolved, but i'll close this issue.

**Closed by jepio** 2023-06-06 10:48 UTC
Labels: question
