### ISSUE TITLE
runtime-rs: implement metrics handler for kata-ctl

### ISSUE THREAD

**Issue by Tim-0731-Hzt** [kata-containers/kata-containers#5368] opened 2022-10-07 06:27 UTC
implement metrics handler with unit test for kata-ctl

**Comment by jodh-intel** [comment] 2022-10-07 08:40
Duplicate of #5342, which I think @amshinde was going to look at, but feel free to collaborate with her! :smile:

**Comment by Tim-0731-Hzt** [comment] 2022-10-07 11:15
same as #5370

**Comment by Ji-Xinyou** [comment] 2022-10-07 12:44
For future assignees who are taking this one, this is already a promethus client implementation in Rust by tikv. You may check [prometheus](https://github.com/tikv/rust-prometheus) for detail.

**Comment by YushuoEdge** [comment] 2022-11-07 02:19
Hi，this feature seems to be a duplicate of https://github.com/kata-containers/kata-containers/issues/5017, and @Yuan-Zhuo is working on that issue.

**Comment by Tim-0731-Hzt** [comment] 2022-11-07 02:31
Thanks, then I will close it

**Closed** 2022-11-07 02:31 UTC
Labels: runtime-rs, kata-ctl
