### ISSUE TITLE
`cleanupVM` not called in some cases for Cloud Hypervisor

### ISSUE THREAD

**Issue by liubin** [kata-containers/kata-containers#1098] opened 2020-11-11 09:26 UTC
In https://github.com/kata-containers/kata-containers/pull/1079 I got some remaining pods under `/run/vc/sbs`, the reason may be that the calling `cleanupVM` in clh.go is not ensured. If the `terminate()` function, we will first try to call `clh.client().ShutdownVMM` and then call `syscall.Kill` if  the  VM is stilling running.  And last `cleanupVM` is called, but if  there is any error in previous calls,  `terminate()` will return immediately and `cleanupVM` will not got to be called.

Comparing to qemu.go, `cleanupVM` is called in a `defer() {} ()` block, that will make sure that the `cleanupVM` will be called.

**Comment by likebreath** [comment] 2020-11-11 23:06
Thanks for opening the issue and tracing down the problem. Your findings are very interesting. I will need to look into the cleanup code path closer. Also, I noticed the log is reporting the VMM is not exiting gracefully, which is also a bit surprise.

```
msg="VM still running after waiting 3s" 
```

I am setting-up a local environment to debug this issue. Interestingly, it looks like your PR #1079 seems to trigger this bug more often. Let me see whether I can reproduce it locally and hopefully I can send a PR to fix the issue soon.

**Comment by liubin** [comment] 2020-11-12 01:55
After https://github.com/kata-containers/kata-containers/pull/1094 has been merged, I test only once, the CLH CI has passed. And I added a debug  commit to "revert" the commit and try to ensure that if there is a causation relationship, but it seems that now the `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0` will not get to start, and always in `triggered` status.

**Comment by likebreath** [comment] 2020-11-12 06:57
I was able to trigger a similar error on my local machine by simply using `ctr` to launch toy containers w/ cloud-hypervisor, and enforcing to call `cleanupVM` did help. That's why I opened a PR #1103 to see how the fix works for your PR.

However, this fix does not resolve the errors on my local machine completely. I still got the vm directory not cleaned up from time to time. When this error happens, I got the error when exiting the container: `"ctr: rpc error: code = Unknown desc = ttrpc: closed: unknown"`, while I got lots of warnings from the `kata-shim-v2` log `"failed to get OOM event from sandbox"`. What's strange is I simply didn't see `stopSandbox` is invoked at all. I will need to dig into it more. 

I am very new to kata 2.0 and containerd/k8s in general. Any questions or comments, please just share. Thanks again for taking the efforts to fix the issue.

**Comment by liubin** [comment] 2020-11-12 07:10
Hi @likebreath ,  http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/454/ has one pod remaining that leads CI failing.

- sandbox id: eba5cd89022d89379eea3f4e4a1cdb2769c0ae522cc1bff44d34e1bf5e457842
- container: 7c6a60f463ee80bd7497ed1780cc78a27e18f731a33f5d855b24f5dba612fc1b

The remaining Pod is not created in k8s test, it is created in `cri-containerd`, but I found the log of containerd is lost, and create an [issue](https://github.com/kata-containers/tests/issues/3054) to track it.

And tested with this debug log https://github.com/kata-containers/kata-containers/pull/1103/commits/af2278e54f50014a4e28833d8858935504490f57 , I got only these logs:

```
03:09:53  time="2020-11-12T03:09:53.08379132Z" level=info msg="Stopping Cloud Hypervisor" PID=20623 pid=20595 sandbox=eba5cd89022d89379eea3f4e4a1cdb2769c0ae522cc1bff44d34e1bf5e457842 source=virtcontainers subsystem=cloudHypervisor

03:09:53  time="2020-11-12T03:09:53.08414004Z" level=info clhRunning=true pid=20595 sandbox=eba5cd89022d89379eea3f4e4a1cdb2769c0ae522cc1bff44d34e1bf5e457842 source=virtcontainers subsystem=cloudHypervisor


03:09:53  time="2020-11-12T03:09:53.197373801Z" level=info msg="before check pidRunning" pid=20595 pidRunning=true sandbox=eba5cd89022d89379eea3f4e4a1cdb2769c0ae522cc1bff44d34e1bf5e457842 source=virtcontainers subsystem=cloudHypervisor


03:09:53  time="2020-11-12T03:09:53.717328968Z" level=info msg="mark agent dead" pid=20595 sandbox=eba5cd89022d89379eea3f4e4a1cdb2769c0ae522cc1bff44d34e1bf5e457842 source=virtcontainers subsystem=kata_agent

03:09:53  time="2020-11-12T03:09:53.723110998Z" level=info msg="mark agent dead" pid=20595 sandbox=eba5cd89022d89379eea3f4e4a1cdb2769c0ae522cc1bff44d34e1bf5e457842 source=virtcontainers subsystem=kata_agent
``` 

No more logs after `before check pidRunning` in the function, but after about 500ms.

**Comment by liubin** [comment] 2020-11-13 03:08
From this [CI job's log](http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/178/)  , I found that a normal Pod (state directory are cleaned) also has many "failed to get OOM event from sandbox".

The failed pod(19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b) and success pod(16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3) have some difference logs. 

The failed one will print a "shim disconnected" log in the shutdown of CLH, but success one will print this log after CLH has shutdown, maybe the connection between containerd and shim is broken.(`ttrpc: closed: unknown`).

The failed log:

```
containerd_03:13289:Nov 12 14:48:01 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:01.942115926Z" level=info msg="Stopping Cloud Hypervisor" PID=30474 pid=30463 sandbox=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b source=virtcontainers subsystem=cloudHypervisor
containerd_03:13291:Nov 12 14:48:01 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:01.945920397Z" level=info clhRunning=true pid=30463 sandbox=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b source=virtcontainers subsystem=cloudHypervisor
containerd_03:15740:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.096767438Z" level=info msg="before check pidRunning" pid=30463 pidRunning=true sandbox=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b source=virtcontainers subsystem=cloudHypervisor
containerd_04:4758:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.493356977Z" level=info msg="StopPodSandbox for \"19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b\""
containerd_04:5393:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.510953230Z" level=info msg="mark agent dead" pid=30463 sandbox=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b source=virtcontainers subsystem=kata_agent
containerd_04:5394:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.533063304Z" level=info msg="mark agent dead" pid=30463 sandbox=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b source=virtcontainers subsystem=kata_agent
containerd_04:5475:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.539505263Z" level=info msg="shim disconnected" id=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b
containerd_04:5476:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.539590069Z" level=warning msg="cleaning up after shim disconnected" id=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b namespace=k8s.io
containerd_04:5478:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.540589540Z" level=error msg="Failed to get task exit status for \"19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b\"" error="ttrpc: closed: unknown"
containerd_04:5479:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.540712449Z" level=debug msg="Received exit event &TaskExit{ContainerID:19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b,ID:19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b,Pid:30463,ExitStatus:255,ExitedAt:2020-11-12 14:48:02.540684347 +0000 UTC m=+198.377109264,XXX_unrecognized:[],}"
containerd_04:5480:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.540752652Z" level=info msg="TaskExit event &TaskExit{ContainerID:19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b,ID:19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b,Pid:30463,ExitStatus:255,ExitedAt:2020-11-12 14:48:02.540684347 +0000 UTC m=+198.377109264,XXX_unrecognized:[],}"
containerd_04:5481:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.594757297Z" level=warning msg="failed to clean up after shim disconnected" error="time=\"2020-11-12T14:48:02Z\" level=warning msg=\"failed to cleanup container\" container=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b error=\"not a Sandbox reference\" pid=31275 sandbox=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b source=containerd-kata-shim-v2\nio.containerd.kata.v2: not a Sandbox reference\n: exit status 1" id=19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b namespace=k8s.io
containerd_04:5484:Nov 12 14:48:02 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:02.608752894Z" level=info msg="TearDown network for sandbox \"19aae2ab97c353a5f8b8334ac45792af995ce20a6a0f8ea0653a215d1664ee3b\" successfully"
```

The success log:

```
containerd_04:5671:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.892621075Z" level=info msg="StopPodSandbox for \"16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3\""
containerd_04:5674:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.893755956Z" level=info msg="StopPodSandbox for \"16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3\""
containerd_04:5677:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.906710978Z" level=warning msg="Could not remove container share dir" error="no such file or directory" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 share-dir=/run/kata-containers/shared/sandboxes/16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3/16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=container
containerd_04:5678:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.907223415Z" level=info msg="Stopping sandbox in the VM" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=sandbox
containerd_04:5680:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.908534808Z" level=info msg="Stopping VM" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=sandbox
containerd_04:5681:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.908591612Z" level=info msg="Stop Sandbox" function=stopSandbox pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:5682:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.908630515Z" level=info msg="Stopping Cloud Hypervisor" PID=31477 pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:5683:Nov 12 14:48:11 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:11.909007942Z" level=info clhRunning=true pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:6340:Nov 12 14:48:12 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:12.006585690Z" level=info msg="before check pidRunning" pid=31466 pidRunning=true sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17321:Nov 12 14:48:12 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:12.602729242Z" level=info msg="mark agent dead" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17322:Nov 12 14:48:12 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:12.602789947Z" level=info msg="mark agent dead" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17377:Nov 12 14:48:13 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:13.600558599Z" level=info msg="mark agent dead" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17378:Nov 12 14:48:13 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:13.600667107Z" level=info msg="mark agent dead" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17417:Nov 12 14:48:14 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:14.600581113Z" level=info msg="mark agent dead" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17418:Nov 12 14:48:14 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:14.600693621Z" level=info msg="mark agent dead" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17452:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.045714712Z" level=warning msg="VM still running after waiting 3s" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17453:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.045859722Z" level=info msg="after check pidRunning" pid=31466 pidRunning=true sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17454:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.045902825Z" level=info msg="stop virtiofsd" PID=31477 pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17455:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.045960829Z" level=info msg="cleanup VM" PID=31477 pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17456:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.046025034Z" level=warning msg="removing vm socket failed" path=/run/vc/vm/16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3/clh.sock pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17457:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.046090938Z" level=info msg="cleanup vm path" dir=/run/vc/vm/16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 link=/run/vc/vm/16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17458:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.046191846Z" level=info msg="Detaching endpoint" endpoint-type=virtual pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=network
containerd_04:17459:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.046903196Z" level=warning msg="sandbox cgroups path is empty" pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=sandbox
containerd_04:17460:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.046962501Z" level=info msg=cleanup function=cleanup pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=cloudHypervisor
containerd_04:17461:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.047007004Z" level=info msg="cleanup agent" path=/run/kata-containers/shared/sandboxes/16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3/shared pid=31466 sandbox=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3 source=virtcontainers subsystem=kata_agent
containerd_04:17462:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.047725655Z" level=debug msg="Received exit event &TaskExit{ContainerID:16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3,ID:16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3,Pid:31466,ExitStatus:9,ExitedAt:2020-11-12 14:48:11.899460562 +0000 UTC,XXX_unrecognized:[],}"
containerd_04:17463:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.047778459Z" level=info msg="TaskExit event &TaskExit{ContainerID:16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3,ID:16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3,Pid:31466,ExitStatus:9,ExitedAt:2020-11-12 14:48:11.899460562 +0000 UTC,XXX_unrecognized:[],}"
containerd_04:17474:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.765702884Z" level=info msg="shim disconnected" id=16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3
containerd_04:17478:Nov 12 14:48:15 ubuntu1804-azure40a120 containerd[23206]: time="2020-11-12T14:48:15.886833310Z" level=info msg="TearDown network for sandbox \"16bf0eb0b3fd8f05bc933b8da643f12add0c18ac2b57c2096d4984c2911f8ee3\" successfully"
```

**Comment by likebreath** [comment] 2020-11-19 00:38
My local experiments with `ctr` is now working fine with the upstream version of runtime. I can confirm that PR #1094 makes a huge difference, and #11011 can also plays a role here (as `virtiofsd` has known crashing issues w/ DAX enabled). Also, we are no longer experiencing similar errors (`pods left and found at /run/vc/sbs`) from the [CI logs](http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/) since the mentioned two PRs were merged. 

After all the `cleanup` procedure should be improved as @liubin suggested here (PR https://github.com/kata-containers/kata-containers/pull/1103). Also, I noticed the way how we stop virtiofsd w/ clh is different from what we do w/ qemu, which I will need to revisit later.

Do you think we are good with the cleanup bug with kata+clh ? Any concerns/questions or findings, please don't hesitate to share. Thank you again for digging into this. @liubin

**Comment by liubin** [comment] 2020-11-19 02:30
@likebreath #1120 will do the cleanup in case of shim disconnected, this will reduce the remaining pods.

**Closed** 2020-12-03 09:34 UTC
Labels: bug, needs-review
