### ISSUE TITLE
Kata not creating symbolic links on mounted ConfigMap

### ISSUE THREAD

**Issue by hleal18** [kata-containers/kata-containers#2950] opened 2021-11-02 16:57 UTC
## Kubelet version

v1.20.11+k3s1 - deployed on k3s.

v1.20.10-gke.2100 - gke cluster.

## Operating System

Ubuntu 20.04.3 LTS

## Kata version

kata-runtime: 2.2.0-alpha1 → 2.3.0-alpha2

# Description of problem

When mounting a ConfigMap the default behavior is for Kubernetes to create hidden folders and some symbolic links between them and the file on the top level. We've found that when using `kata-clh` runtime class this is not the case. Rather than symbolic links being created, the original files are used instead.

This affects the behavior of commands that scan for scripts on the mounted folder, as using the following command `find -type f` will show the same file three times: 

- The mounted file.
- The file inside the `..{DATE}` folder
- The file inside the `..data` folder

This interferes with our operation of certain helm charts as the initialization scripts loaded from a ConfigMap will mistakenly get executed three times which is not desired.

We have attached more information about the expected outcome and the behavior we're experiencing.

# Sample Manifests

The following are the Kubernetes resources used to reproduce the issue. Once deployed, exec into the container and go to the `/scripts` folder:

```bash
kubectl exec {nginx-pod-name} -i -t -- /bin/bash
cd /scripts
```

### Deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: scripts
        configMap:
          name: nginx-configmap
      runtimeClassName: kata-clh
```

### ConfigMap

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  init-script.sh: |
    #!/bin/bash
    echo "Hello there"
```

# Expected result

Using the previous manifests without a runtime class, inspecting the mounted folder on the `/scripts` path, which contains one file called `init-script.sh` , we can observe the expected results after running `ls -la`:

```jsx
/scripts$ ls -la
total 13
drwxrwxrwx 3 root root 4096 Oct 29 03:10 .
drwxr-xr-x 1 root root 4096 Oct 29 03:11 ..
drwxr-xr-x 2 root root 4096 Oct 29 03:10 ..2021_10_29_03_10_48.161654083
lrwxrwxrwx 1 root root   31 Oct 29 03:10 ..data -> ..2021_10_29_03_10_48.161654083
lrwxrwxrwx 1 root root   21 Oct 29 03:10 init-script.sh -> ..data/init-script.sh
```

Symbolic links from the `init-script.sh` on the top level to the file located at`..data/init-script.sh` . Similarly, a symlink from the `..data` folder to the `..2021_10_29_03_10_48.161654083` folder is observed.

Running `ls -la` from each subfolder shows the following output.

- `/scripts/..2021_10_29_03_10_48.161654083` :

```jsx
/scripts/..2021_10_29_03_10_48.161654083$ ls -la
total 9
drwxr-xr-x 2 root root 4096 Oct 29 03:10 .
drwxrwxrwx 3 root root 4096 Oct 29 03:10 ..
-rw-r--r-- 1 root root   31 Oct 29 03:10 init-script.sh
```

- `/scripts/..data` :

```jsx
/scripts/..data$ ls -la
total 9
drwxr-xr-x 2 root root 4096 Oct 29 03:10 .
drwxrwxrwx 3 root root 4096 Oct 29 03:10 ..
-rw-r--r-- 1 root root   31 Oct 29 03:10 init-script.sh
```

# Actual result

Now with the same deployment and configmap but now using `kata-clh` runtime class, running the same `ls -la` command:

```jsx
/scripts$ ls -la
total 12
drwxr-xr-x 4 root root  100 Oct 29 02:50 .
drwxr-xr-x 1 root root 4096 Oct 29 02:50 ..
drwxr-xr-x 2 root root   60 Oct 29 02:50 ..2021_10_29_02_50_12.610733714
drwxr-xr-x 2 root root   60 Oct 29 02:50 ..data
-rw-r--r-- 1 root root   31 Oct 29 02:50 init-script.sh
```

The symbolic links are not there anymore. 

Running  `ls -la` from `/script/..2021_10_29_02_50_12.610733714` shows the following results:

```jsx
/scripts/..2021_10_29_02_50_12.610733714$ ls -la
total 4
drwxr-xr-x 2 root root  60 Oct 29 02:50 .
drwxr-xr-x 4 root root 100 Oct 29 02:50 ..
-rw-r--r-- 1 root root  31 Oct 29 02:50 init-script.sh
```

Running `ls -la` from `/scripts/..data` shows the following results:

```jsx
/scripts/..data$ ls -la
total 4
drwxr-xr-x 2 root root  60 Oct 29 02:50 .
drwxr-xr-x 4 root root 100 Oct 29 02:50 ..
-rw-r--r-- 1 root root  31 Oct 29 02:50 init-script.sh
```

# Further Information

We've tried different versions of kata-runtime. We tested `2.1.1`, `2.2.0-alpha0` , `2.2.0-alpha1`, `2.2.0` and `2.3.0-alpha2`. The only ones that worked as expected were `2.1.1` and `2.2.0-alpha0`, hence, we believe the change might have been introduced at `2.2.0-alpha1`. We hope this serves as a good starting point for looking into this issue.

**Comment by fidencio** [comment] 2021-11-02 22:15
@hleal18, does this only happen with cloud-hypervisor?
@egernst, @lifupan, does this ring any bell?

**Comment by hleal18** [comment] 2021-11-03 11:48
@fidencio, tested also with `kata-qemu-virtiofs` runtimeClass and the issue persists

**Comment by fidencio** [comment] 2021-11-03 12:51
@hleal18, thanks for confirming it.  Then the problem is not related to the hypervisor, but most likely on the agent.
I think Eric or Li could have a better idea of this and, for now, I'll add the right tags to the issue report.

**Comment by egernst** [comment] 2021-11-04 18:58
@hleal18 - Great issue report -- appreciate all of the details, it makes it easier to triage for sure!

This is introduced in more recent releases because of a feature to allow for fsnotify to work with configmaps, secrets. See https://github.com/kata-containers/kata-containers/blob/main/docs/design/inotify.md

I won't be able to dig into this right away, but I'm confident this is mishandling here https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/watcher.rs#L93

**Comment by egernst** [comment] 2021-11-08 22:26
What we need is a copy which does NOT dereference symlinks, instead copying the relative link, here: https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/watcher.rs#L119

This would be equivalent of `cp -d` on a host (ie: `--no-dereference --preserve=links`). I did a quick search and didn't readily see this supported in the existing fs crate.

**Comment by egernst** [comment] 2021-11-11 17:21
@hleal18 -- not sure how much you'd be up for it -- but I have a PR in place that resolves this issue, as well as an integration test outstanding. Want to take a look at the proposed test? https://github.com/kata-containers/tests/pull/4181

Or, any chance you want to verify the fix for your use case (if you're used to building from src!)?

**Comment by hleal18** [comment] 2021-11-11 17:41
Thanks @egernst, we'll build and test the pr tomorrow and let you know how it goes.

**Comment by hleal18** [comment] 2021-11-12 13:24
@egernst we tested the pr. The situation has improved, the symlink from the file on the top level to the one located inside of the `..data` folder is there. However, the symlink from the `..data` folder to the `..{DATE}` is still missing.
This causes the `find . -type f` command to report two files.
I attach the output that we’re getting with the pr that contains the fix so you can easily compare it with the one attached on the GitHub issue.
Let us know if you need more details.

`ls -la` command:

```
root@nginx-deployment-kata-clh-759b5b5c4f-5klpb:/scripts# ls -la
total 8
drwxr-xr-x 4 root root  100 Nov 12 12:56 .
drwxr-xr-x 1 root root 4096 Nov 12 12:56 ..
drwxr-xr-x 2 root root   60 Nov 12 12:56 ..2021_11_12_12_56_48.911892494
drwxr-xr-x 2 root root   60 Nov 12 12:56 ..data
lrwxrwxrwx 1 root root   21 Nov 12 12:56 init-script.sh -> ..data/init-script.sh
```

`find . -type f` command;

```
root@nginx-deployment-kata-clh-759b5b5c4f-5klpb:/scripts# find . -type f
./..2021_11_12_12_56_48.911892494/init-script.sh
./..data/init-script.sh
```

**Comment by egernst** [comment] 2021-11-12 15:20
Yikes, that's unexpected. Thanks for testing, appreciate the help!

**Comment by egernst** [comment] 2021-11-18 18:12
Hope you are well @hleal18  -- I believe we have this fixed now! If you can take a look, I'd appreciate it. https://github.com/kata-containers/kata-containers/pull/2998

**Closed** 2021-11-19 20:43 UTC
Labels: bug, area/agent

**Comment by hleal18** [comment] 2021-11-24 15:52
Hi @egernst, sorry the delay. 

We've tested it and can confirm that it fixes the issue, thanks for taking care of it.
