### ISSUE TITLE
Fix warnings when build with Cargo 1.68

### ISSUE THREAD

**Issue by Apokleos** [kata-containers/kata-containers#6593] opened 2023-04-04 03:28 UTC
**Which feature do you think can be improved?**

Fix warning when build with rust cargo 1.68

```
...
warning: this `impl` can be derived
  --> crates/agent/src/types.rs:23:1
   |
23 | / impl Default for FSGroupChangePolicy {
24 | |     fn default() -> Self {
25 | |         FSGroupChangePolicy::Always
26 | |     }
27 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
   = note: `#[warn(clippy::derivable_impls)]` on by default
   = help: remove the manual implementation...
help: ...and instead derive it...
   |
30 | #[derive(Default)]
   |
help: ...and mark the default variant
   |
31 ~     #[default]
32 ~     Always = 0,
   |

warning: this `impl` can be derived
  --> crates/agent/src/types.rs:74:1
   |
74 | / impl ::std::default::Default for IPFamily {
75 | |     fn default() -> Self {
76 | |         IPFamily::V4
77 | |     }
78 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
   = help: remove the manual implementation...
help: ...and instead derive it...
   |
69 | #[derive(Default)]
   |
help: ...and mark the default variant
   |
70 ~     #[default]
71 ~     V4 = 0,
   |

warning: `agent` (lib) generated 2 warnings
    Checking resource v0.1.0 (kata-containers/src/runtime-rs/crates/resource)
warning: unneeded `return` statement
  --> crates/resource/src/rootfs/mod.rs:82:21
   |
82 |                     return Err(anyhow!("share fs is unavailable"));
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

**Comment by Tim-Zhang** [comment] 2023-04-17 09:51
Duplicate of https://github.com/kata-containers/kata-containers/pull/5754

**Closed** 2023-05-10 01:51 UTC
Labels: enhancement, needs-review
